import type { SkillContent } from "./types";

/**
 * Content registry: maps a skill slug to a lazy loader for its full page.
 * Lazy imports keep each skill's (large) content out of the shared bundle —
 * a page only ships the content it renders.
 *
 * To add a skill: create src/content/skills/<slug>.ts, register it here,
 * and set the skill's status to "done" in src/data/catalog.ts.
 */
const REGISTRY: Record<string, () => Promise<{ default: SkillContent }>> = {
  python: () => import("./skills/python"),
  javascript: () => import("./skills/javascript"),
  typescript: () => import("./skills/typescript"),
  go: () => import("./skills/go"),
  rust: () => import("./skills/rust"),
  java: () => import("./skills/java"),
  fastapi: () => import("./skills/fastapi"),
  cpp: () => import("./skills/cpp"),
  django: () => import("./skills/django"),
  flask: () => import("./skills/flask"),
  express: () => import("./skills/express"),
  "spring-boot": () => import("./skills/spring-boot"),
  nodejs: () => import("./skills/nodejs"),
  nestjs: () => import("./skills/nestjs"),
  postgresql: () => import("./skills/postgresql"),
  mysql: () => import("./skills/mysql"),
  mongodb: () => import("./skills/mongodb"),
  redis: () => import("./skills/redis"),
  neo4j: () => import("./skills/neo4j"),
  elasticsearch: () => import("./skills/elasticsearch"),
  clickhouse: () => import("./skills/clickhouse"),
  sqlite: () => import("./skills/sqlite"),
  faiss: () => import("./skills/faiss"),
  pinecone: () => import("./skills/pinecone"),
  milvus: () => import("./skills/milvus"),
  weaviate: () => import("./skills/weaviate"),
  qdrant: () => import("./skills/qdrant"),
  chroma: () => import("./skills/chroma"),
  oauth: () => import("./skills/oauth"),
  jwt: () => import("./skills/jwt"),
  "cookies-sessions": () => import("./skills/cookies-sessions"),
  rbac: () => import("./skills/rbac"),
  abac: () => import("./skills/abac"),
  rest: () => import("./skills/rest"),
  graphql: () => import("./skills/graphql"),
  grpc: () => import("./skills/grpc"),
  websockets: () => import("./skills/websockets"),
  sse: () => import("./skills/sse"),
  linux: () => import("./skills/linux"),
  networking: () => import("./skills/networking"),
  "operating-systems": () => import("./skills/operating-systems"),
  dsa: () => import("./skills/dsa"),
  algorithms: () => import("./skills/algorithms"),
  oop: () => import("./skills/oop"),
  solid: () => import("./skills/solid"),
  "design-patterns": () => import("./skills/design-patterns"),
  concurrency: () => import("./skills/concurrency"),
  multithreading: () => import("./skills/multithreading"),
  "caching-cs": () => import("./skills/caching-cs"),
  "sql-injection": () => import("./skills/sql-injection"),
  xss: () => import("./skills/xss"),
  csrf: () => import("./skills/csrf"),
  encryption: () => import("./skills/encryption"),
  hashing: () => import("./skills/hashing"),
  "tls-https": () => import("./skills/tls-https"),
  "secrets-management": () => import("./skills/secrets-management"),
  "owasp-top-10": () => import("./skills/owasp-top-10"),
  aws: () => import("./skills/aws"),
  azure: () => import("./skills/azure"),
  gcp: () => import("./skills/gcp"),
  docker: () => import("./skills/docker"),
  kubernetes: () => import("./skills/kubernetes"),
  terraform: () => import("./skills/terraform"),
  cicd: () => import("./skills/cicd"),
  "github-actions": () => import("./skills/github-actions"),
  jenkins: () => import("./skills/jenkins"),
  git: () => import("./skills/git"),
  logging: () => import("./skills/logging"),
  metrics: () => import("./skills/metrics"),
  tracing: () => import("./skills/tracing"),
  prometheus: () => import("./skills/prometheus"),
  grafana: () => import("./skills/grafana"),
  opentelemetry: () => import("./skills/opentelemetry"),
  "distributed-systems": () => import("./skills/distributed-systems"),
  "cap-theorem": () => import("./skills/cap-theorem"),
  "load-balancers": () => import("./skills/load-balancers"),
  "reverse-proxy": () => import("./skills/reverse-proxy"),
  "api-gateway": () => import("./skills/api-gateway"),
  cdn: () => import("./skills/cdn"),
  "caching-systems": () => import("./skills/caching-systems"),
  "message-queues": () => import("./skills/message-queues"),
  kafka: () => import("./skills/kafka"),
  rabbitmq: () => import("./skills/rabbitmq"),
  "prompt-injection-defense": () => import("./skills/prompt-injection-defense"),
  "ai-red-teaming": () => import("./skills/ai-red-teaming"),
  llmops: () => import("./skills/llmops"),
  "prompt-versioning": () => import("./skills/prompt-versioning"),
  "model-routing": () => import("./skills/model-routing"),
  langsmith: () => import("./skills/langsmith"),
  langfuse: () => import("./skills/langfuse"),
  llamaindex: () => import("./skills/llamaindex"),
  dspy: () => import("./skills/dspy"),
  "pydantic-ai": () => import("./skills/pydantic-ai"),
  "machine-learning": () => import("./skills/machine-learning"),
  "deep-learning": () => import("./skills/deep-learning"),
  "neural-networks": () => import("./skills/neural-networks"),
  cnn: () => import("./skills/cnn"),
  rnn: () => import("./skills/rnn"),
  transformers: () => import("./skills/transformers"),
  attention: () => import("./skills/attention"),
  embeddings: () => import("./skills/embeddings"),
  "vector-search": () => import("./skills/vector-search"),
  "llm-fundamentals": () => import("./skills/llm-fundamentals"),
  "prompt-engineering": () => import("./skills/prompt-engineering"),
  "fine-tuning": () => import("./skills/fine-tuning"),
  inference: () => import("./skills/inference"),
  serving: () => import("./skills/serving"),
  evaluation: () => import("./skills/evaluation"),
  hallucination: () => import("./skills/hallucination"),
  guardrails: () => import("./skills/guardrails"),
  "agents-fundamentals": () => import("./skills/agents-fundamentals"),
  langchain: () => import("./skills/langchain"),
  langgraph: () => import("./skills/langgraph"),
  crewai: () => import("./skills/crewai"),
  "openai-agents-sdk": () => import("./skills/openai-agents-sdk"),
  autogen: () => import("./skills/autogen"),
  "agent-memory": () => import("./skills/agent-memory"),
  planning: () => import("./skills/planning"),
  reflection: () => import("./skills/reflection"),
  "tool-calling": () => import("./skills/tool-calling"),
  mcp: () => import("./skills/mcp"),
  "rag-fundamentals": () => import("./skills/rag-fundamentals"),
  "knowledge-graphs": () => import("./skills/knowledge-graphs"),
  ontology: () => import("./skills/ontology"),
  "graph-databases": () => import("./skills/graph-databases"),
  "ai-monitoring": () => import("./skills/ai-monitoring"),
  "cost-optimization": () => import("./skills/cost-optimization"),
  latency: () => import("./skills/latency"),
  streaming: () => import("./skills/streaming"),
  "ai-evals": () => import("./skills/ai-evals"),
  "ai-harness": () => import("./skills/ai-harness"),
  "context-engineering": () => import("./skills/context-engineering"),
  "semantic-caching": () => import("./skills/semantic-caching"),
  "a2a-protocol": () => import("./skills/a2a-protocol"),
  "multi-agent-systems": () => import("./skills/multi-agent-systems"),
  "agent-observability": () => import("./skills/agent-observability"),
  "human-in-the-loop": () => import("./skills/human-in-the-loop"),
  vllm: () => import("./skills/vllm"),
  ollama: () => import("./skills/ollama"),
  sglang: () => import("./skills/sglang"),
  "structured-outputs": () => import("./skills/structured-outputs"),
  "openai-responses-api": () => import("./skills/openai-responses-api"),
  "openai-realtime-api": () => import("./skills/openai-realtime-api"),
  "claude-code": () => import("./skills/claude-code"),
  "ai-scaling": () => import("./skills/ai-scaling"),
  "realtime-ai": () => import("./skills/realtime-ai"),
  "voice-ai": () => import("./skills/voice-ai"),
  "vision-ai": () => import("./skills/vision-ai"),
  ocr: () => import("./skills/ocr"),
  "image-generation": () => import("./skills/image-generation"),
  "video-models": () => import("./skills/video-models"),
  "mlops-fundamentals": () => import("./skills/mlops-fundamentals"),
  mlflow: () => import("./skills/mlflow"),
  kubeflow: () => import("./skills/kubeflow"),
  wandb: () => import("./skills/wandb"),
  "feature-stores": () => import("./skills/feature-stores"),
  airflow: () => import("./skills/airflow"),
  spark: () => import("./skills/spark"),
  "data-pipelines": () => import("./skills/data-pipelines"),
};

export const hasContent = (slug: string): boolean => slug in REGISTRY;

export async function loadContent(slug: string): Promise<SkillContent | null> {
  const loader = REGISTRY[slug];
  if (!loader) return null;
  return (await loader()).default;
}
