import type { CheatSheetData } from "./types";

const aws: CheatSheetData = {
  title: "The Ultimate AWS Cheat Sheet",
  subtitle: "Core services · networking · IAM · production toolbelt",
  sections: [
    {
      title: "Identity & Access (IAM)",
      color: "violet",
      rows: [
        { term: "IAM user", desc: "Long-lived identity, typically a person", code: "aws iam create-user --user-name ada" },
        { term: "IAM role", desc: "Temporary identity assumed by a person or service", code: "sts:AssumeRole\nUsed by EC2 instance profiles, Lambda exec roles" },
        { term: "Policy", desc: "JSON document: Effect + Action + Resource", code: "{ \"Effect\": \"Allow\",\n  \"Action\": [\"s3:GetObject\"],\n  \"Resource\": \"arn:aws:s3:::bucket/*\" }" },
        { term: "Policy evaluation", desc: "Order that decides Allow vs Deny", code: "1. Default deny\n2. Explicit Deny anywhere wins\n3. Explicit Allow grants access" },
        { term: "Permissions boundary", desc: "Caps what an identity policy can ever grant", code: "Used so teams can create roles\nwithout escalating privilege" },
        { term: "SCP", desc: "Org-level guardrail across accounts/OUs", code: "Deny leaving an approved region\nDeny disabling CloudTrail" },
        { term: "Who am I?", desc: "First command in any unfamiliar account", code: "aws sts get-caller-identity" },
        { term: "Root account rule", desc: "Lock behind MFA, never use day to day", code: "Daily work = IAM roles/users,\nnot the root login" },
        { term: "Least privilege", desc: "Start from zero, add only proven-needed actions", code: "Never: \"Action\": \"*\", \"Resource\": \"*\"" },
        { term: "IAM Access Analyzer", desc: "Finds unused permissions and unintended public access", code: "aws accessanalyzer list-findings\n  --analyzer-arn <arn>" },
      ],
    },
    {
      title: "Compute",
      color: "blue",
      rows: [
        { term: "EC2", desc: "Virtual machines — full OS control", code: "aws ec2 run-instances --image-id ami-x\n  --instance-type t3.micro --key-name kp" },
        { term: "AMI / instance type", desc: "Boot template / vCPU-memory-network profile", code: "g-suffix families = Graviton (ARM)\nbest price-performance default" },
        { term: "Lambda", desc: "Event-driven, no servers, pay per invocation", code: "def handler(event, context):\n    return {\"statusCode\": 200, \"body\": \"ok\"}" },
        { term: "Lambda lifecycle", desc: "Init (cold start) -> Invoke -> Shutdown", code: "Init clients/DB connections OUTSIDE\nthe handler — reused across warm calls" },
        { term: "ECS", desc: "AWS-native container orchestration", code: "aws ecs run-task --cluster c --task-definition td" },
        { term: "EKS", desc: "Managed Kubernetes control plane", code: "See the Kubernetes skill for depth" },
        { term: "Fargate", desc: "Serverless compute for ECS or EKS tasks/pods", code: "No EC2 instances to patch or manage" },
        { term: "Auto Scaling Group", desc: "Maintains fleet size between min/max on a metric", code: "Target tracking on CPU or\nRequestCountPerTarget" },
        { term: "Compute choice rule", desc: "Match workload shape to operational overhead", code: "Bursty/event -> Lambda\nSteady state -> ECS/EKS(+Fargate)\nSpecial HW -> EC2" },
      ],
    },
    {
      title: "Storage & Databases",
      color: "emerald",
      rows: [
        { term: "S3", desc: "Object storage — buckets + keys, not a filesystem", code: "aws s3 cp file.txt s3://bucket/key.txt\naws s3 ls s3://bucket/prefix/" },
        { term: "S3 durability", desc: "Erasure-coded across 3+ AZs", code: "99.999999999% (11 nines) annual durability" },
        { term: "S3 storage classes", desc: "Trade retrieval speed for price", code: "Standard -> Infrequent Access -> Glacier" },
        { term: "S3 lifecycle rule", desc: "Auto-transition/expire objects by age", code: "{ \"Transitions\": [{\"Days\":30,\"StorageClass\":\"GLACIER\"}],\n  \"Expiration\": {\"Days\":365} }" },
        { term: "EBS", desc: "Block storage attached to one EC2 instance", code: "Like a virtual disk — persists\nindependent of instance lifecycle" },
        { term: "EFS", desc: "Shared file storage, mountable by many instances", code: "NFS-based, scales automatically" },
        { term: "RDS", desc: "Managed relational DB — Postgres/MySQL/etc", code: "Multi-AZ = sync standby,\nauto failover in ~60-120s" },
        { term: "Aurora", desc: "AWS-native relational engine, faster failover", code: "6-way replication across 3 AZs,\nfailover typically under 30s" },
        { term: "DynamoDB", desc: "Managed key-value/NoSQL, scales by partition key", code: "Hot partition = low-cardinality key\nWrite-shard with a random suffix" },
        { term: "ElastiCache", desc: "Managed Redis/Memcached for caching", code: "10-100x latency win for read-heavy paths" },
      ],
    },
    {
      title: "Networking",
      color: "amber",
      rows: [
        { term: "VPC", desc: "Isolated network, defined by a CIDR block", code: "VPC 10.0.0.0/16\n  public 10.0.1.0/24, private 10.0.11.0/24" },
        { term: "Public subnet", desc: "Route to an Internet Gateway", code: "0.0.0.0/0 -> igw-xxxx" },
        { term: "Private subnet", desc: "Route to a NAT Gateway, outbound only", code: "0.0.0.0/0 -> nat-xxxx (in a public subnet)" },
        { term: "Security group", desc: "Stateful, allow-only, instance/ENI-scoped", code: "aws ec2 authorize-security-group-ingress\n  --group-id sg-app --source-group sg-alb" },
        { term: "NACL", desc: "Stateless, allow+deny, subnet-scoped", code: "Coarse secondary layer, rarely\ndoes the primary access-control work" },
        { term: "ALB", desc: "Layer 7 — HTTP/HTTPS routing, TLS termination", code: "Path/host-based routing,\nWAF integration" },
        { term: "NLB", desc: "Layer 4 — TCP/UDP, ultra-low latency", code: "Preserves client source IP,\nmillions of req/sec" },
        { term: "VPC Endpoint", desc: "Private route to an AWS service", code: "Gateway (S3/DynamoDB, free)\nInterface (most others, PrivateLink)" },
        { term: "Transit Gateway", desc: "Hub-and-spoke router for many VPCs", code: "Use once VPC Peering (pairwise)\nstops scaling" },
        { term: "Least-privilege chain", desc: "Each tier only accepts from the one above it", code: "internet -> ALB SG -> app SG -> db SG\nnothing further" },
      ],
    },
    {
      title: "Pitfalls & Gotchas",
      color: "rose",
      rows: [
        { term: "Public S3 bucket", desc: "Most common real-world breach vector", code: "Enable S3 Block Public Access\naccount-wide as a backstop" },
        { term: "Overly broad IAM policy", desc: "One leaked key = full account compromise", code: "Never \"Action\": \"*\", \"Resource\": \"*\"\non a real workload role" },
        { term: "Hardcoded credentials", desc: "Permanent liability once committed anywhere", code: "Use an instance profile / execution role\ninstead of embedded keys" },
        { term: "Single-AZ prod database", desc: "One AZ event = one outage", code: "Set Multi-AZ = true for every\nstateful production resource" },
        { term: "SSH/RDP open to 0.0.0.0/0", desc: "Immediately exploitable exposure", code: "Use Session Manager instead\nof exposing port 22/3389" },
        { term: "IMDS SSRF risk", desc: "SSRF can fetch instance IAM credentials", code: "Enforce IMDSv2 (session token)\naccount-wide" },
        { term: "No tagging", desc: "Untagged resources are cost/ownership blind spots", code: "Tag on creation: env, owner,\ncost-center, app" },
        { term: "Local disk state", desc: "Instances are ephemeral, disk is not durable state", code: "Store sessions/files in\nS3, DynamoDB, or Redis" },
        { term: "Default VPC in prod", desc: "Meant for quick starts, not deliberate isolation", code: "Design a custom VPC for\nproduction workloads" },
        { term: "Untested IAM policy", desc: "Assuming a hand-written policy does what you meant", code: "aws iam simulate-principal-policy\n  --policy-source-arn <arn>" },
      ],
    },
    {
      title: "Cost Optimization",
      color: "cyan",
      rows: [
        { term: "On-demand", desc: "Pay per second/hour, no commitment", code: "Default for new or unpredictable workloads" },
        { term: "Reserved Instances", desc: "1-3yr commitment, steady workloads", code: "Up to ~70% off vs on-demand" },
        { term: "Savings Plans", desc: "Flexible commitment across families/compute types", code: "Covers EC2, Fargate, Lambda" },
        { term: "Spot Instances", desc: "Spare capacity, can be reclaimed", code: "Up to ~90% off — stateless/\nbatch/fault-tolerant workloads only" },
        { term: "Right-sizing", desc: "Match instance size to real utilization", code: "aws compute-optimizer\n  get-ec2-instance-recommendations" },
        { term: "Budgets + alerts", desc: "Set before provisioning, not after the bill", code: "Configure a threshold alert\non day one of any new account" },
        { term: "Graviton", desc: "ARM instance family, strong price-performance", code: "Default starting point for\nnew compatible workloads" },
      ],
    },
    {
      title: "Observability & Ops Toolbelt",
      color: "violet",
      rows: [
        { term: "CloudWatch", desc: "Metrics, logs, alarms, dashboards", code: "aws cloudwatch put-metric-alarm\n  --alarm-name x --threshold 10 ..." },
        { term: "CloudWatch Logs Insights", desc: "Query logs for fast root-cause search", code: "fields @timestamp, @message\n| filter @message like /ERROR/" },
        { term: "X-Ray", desc: "Distributed tracing across service boundaries", code: "Shows which hop dominates request latency" },
        { term: "CloudTrail", desc: "Audit log of every API call, who and when", code: "First stop after an unexplained\nconfig change or incident" },
        { term: "GuardDuty", desc: "ML-based continuous threat detection", code: "Flags credential exfiltration,\ncrypto-mining patterns" },
        { term: "Security Hub", desc: "Aggregated, prioritized security findings", code: "Combines GuardDuty, Config,\nInspector against CIS benchmarks" },
        { term: "AWS Config", desc: "Continuous compliance/drift detection", code: "Rule: no SG allows 0.0.0.0/0 on port 22" },
        { term: "VPC Reachability Analyzer", desc: "Why can't A reach B — static path analysis", code: "Checks route tables, SGs, NACLs\nwithout generating real traffic" },
        { term: "IaC toolchain", desc: "Provision through code, not console clicks", code: "Terraform (multi-cloud) or\nCloudFormation/CDK (AWS-native)" },
        { term: "Secrets storage", desc: "Never plaintext env vars with secrets baked in", code: "Secrets Manager / Parameter Store,\nfetched at runtime via IAM role" },
      ],
    },
  ],
};

export default aws;
