import type { CheatSheetData } from "./types";

const cookiesSessions: CheatSheetData = {
  title: "The Ultimate Cookies and Sessions Cheat Sheet",
  subtitle: "Cookie anatomy · session lifecycle · attacks and defenses · production toolbelt",
  sections: [
    {
      title: "Cookie Anatomy & Attributes",
      color: "violet",
      rows: [
        { term: "Set-Cookie (response)", desc: "Server asks the browser to store a name/value pair", code: "Set-Cookie: sessionId=abc123; Path=/;\n  Secure; HttpOnly; SameSite=Lax" },
        { term: "Cookie (request)", desc: "Browser replays matching cookies automatically", code: "GET /dashboard HTTP/1.1\nCookie: sessionId=abc123" },
        { term: "name=value", desc: "Only part app code should read — keep it opaque", code: "sessionId=8f14e45fceea167a5a36" },
        { term: "Domain", desc: "Omit for exact-host only; set to share across subdomains", code: "Domain=example.com  # shared with\n  # api.example.com, admin.example.com" },
        { term: "Path", desc: "Restricts which URL paths receive the cookie", code: "Path=/           # everywhere on the domain\nPath=/admin      # only that subtree" },
        { term: "Expires", desc: "Absolute date the cookie dies — clock-skew sensitive", code: "Expires=Wed, 09 Jun 2027 10:18:14 GMT" },
        { term: "Max-Age", desc: "Relative seconds until expiry — preferred over Expires", code: "Max-Age=3600   # 1 hour\nMax-Age=0      # delete immediately" },
        { term: "No Expires/Max-Age", desc: "Makes it a session cookie — dies when browser closes", code: "Set-Cookie: temp=1; Path=/" },
        { term: "Secure", desc: "Only ever sent over HTTPS, never plain HTTP", code: "Set-Cookie: sid=x; Secure" },
        { term: "HttpOnly", desc: "Blocks ALL JavaScript access — the main XSS-theft defense", code: "Set-Cookie: sid=x; HttpOnly\n// document.cookie cannot see it" },
        { term: "SameSite=Strict", desc: "Never sent on any cross-site request, even navigation", code: "SameSite=Strict  # safest, some login friction" },
        { term: "SameSite=Lax", desc: "Sent on top-level cross-site GET nav, withheld elsewhere", code: "SameSite=Lax  # modern browser default" },
        { term: "SameSite=None", desc: "Sent on every cross-site request — requires Secure", code: "SameSite=None; Secure  # legit cross-site embeds only" },
        { term: "__Host- prefix", desc: "Browser enforces Secure + Path=/ + no Domain", code: "Set-Cookie: __Host-sid=x; Secure; Path=/" },
        { term: "__Secure- prefix", desc: "Browser enforces Secure only", code: "Set-Cookie: __Secure-flag=1; Secure" },
        { term: "Size limits", desc: "Browsers cap roughly 4KB per cookie, limited count/domain", code: "// keep cookie value to an ID, not a payload" },
      ],
    },
    {
      title: "Session Lifecycle & Storage",
      color: "blue",
      rows: [
        { term: "Session ID generation", desc: "Always a CSPRNG, never Math.random or a counter", code: "python: secrets.token_hex(32)\nnode:   crypto.randomBytes(32).toString('hex')" },
        { term: "Entropy requirement", desc: "128+ bits so brute-force guessing is infeasible", code: "32 hex chars = 128 bits minimum" },
        { term: "In-memory store", desc: "Dev only — dies on restart, not shared across instances", code: "const store = new Map();  // single process only" },
        { term: "Redis-backed store", desc: "Production default — shared, fast, native TTL", code: "SET sess:abc123 '{...}' EX 1800\nGET sess:abc123\nDEL sess:abc123" },
        { term: "Database-backed store", desc: "Durable and queryable; slower, needs its own cleanup", code: "SELECT * FROM sessions WHERE id = 'abc123'\n  AND expires_at > now()" },
        { term: "Login: create session", desc: "Verify creds, then write fresh session data", code: "session.userId = user.id\nsession.createdAt = Date.now()" },
        { term: "Regenerate on login", desc: "New session ID at login — the fixation defense", code: "req.session.regenerate(cb)\n// THEN attach user data to the new id" },
        { term: "Idle timeout", desc: "Expires after N minutes with no activity, resets per request", code: "cookie: { maxAge: 30 * 60 * 1000 }, rolling: true" },
        { term: "Absolute timeout", desc: "Expires N hours after login no matter how active", code: "if (now - session.createdAt > 12 * 3600 * 1000)\n  invalidate(session)" },
        { term: "Logout = real revocation", desc: "Delete the STORE record, not just the client cookie", code: "await redis.del('sess:' + sessionId)\nres.clearCookie('sessionId')" },
        { term: "Store TTL matches cookie", desc: "Server-side expiry should mirror Max-Age", code: "redis.set(key, data, { EX: 1800 })  // 30 min" },
        { term: "Sign out everywhere", desc: "Delete every session record for a user id", code: "for (const id of await sessionsFor(userId))\n  await redis.del('sess:' + id)" },
      ],
    },
    {
      title: "Everyday Idioms",
      color: "emerald",
      rows: [
        { term: "Express: set cookie", desc: "res.cookie with hardened options", code: "res.cookie('sessionId', id, {\n  httpOnly: true, secure: true, sameSite: 'lax' })" },
        { term: "Express: read cookie", desc: "Requires cookie-parser middleware", code: "app.use(require('cookie-parser')())\nconst id = req.cookies.sessionId" },
        { term: "Express: session middleware", desc: "express-session + connect-redis in one line", code: "app.use(session({ store: redisStore,\n  secret: process.env.SESSION_SECRET }))" },
        { term: "Flask: set cookie", desc: "make_response + set_cookie", code: "resp = make_response({'ok': True})\nresp.set_cookie('sessionId', sid, httponly=True,\n  secure=True, samesite='Lax')" },
        { term: "Flask-Session: server-side", desc: "Swap Flask's default signed cookie for Redis", code: "app.config['SESSION_TYPE'] = 'redis'\napp.config['SESSION_REDIS'] = redis_client" },
        { term: "Django: session settings", desc: "Settings that harden the built-in session framework", code: "SESSION_COOKIE_SECURE = True\nSESSION_COOKIE_HTTPONLY = True\nSESSION_COOKIE_SAMESITE = 'Lax'" },
        { term: "Django: use a session", desc: "Dict-like request.session", code: "request.session['user_id'] = user.id\nrequest.session.cycle_key()  # regenerate id" },
        { term: "Reading a cookie in JS (non-HttpOnly)", desc: "Only for NON-sensitive cookies", code: "document.cookie.split('; ')\n  .find(row => row.startsWith('theme='))" },
        { term: "curl: inspect Set-Cookie", desc: "Fastest way to debug cookie attributes", code: "curl -i -X POST https://example.com/login\n  -d 'user=a&pass=b'" },
        { term: "curl: replay a cookie jar", desc: "Reproduce a session bug outside the browser", code: "curl --cookie-jar jar.txt --cookie jar.txt\n  https://example.com/dashboard" },
      ],
    },
    {
      title: "Attacks & Defenses",
      color: "amber",
      rows: [
        { term: "Session fixation", desc: "Attacker plants a known ID, victim logs in under it", code: "Defense: regenerate session ID at login\n  and at privilege escalation" },
        { term: "Session hijacking", desc: "Attacker steals a valid ID and replays it", code: "Defense: HttpOnly + Secure + short expiry,\n  never log raw session IDs" },
        { term: "Session prediction", desc: "Attacker guesses a weakly-generated ID", code: "Defense: CSPRNG, 128+ bits of entropy" },
        { term: "CSRF", desc: "Cross-site request rides the auto-attached cookie", code: "Defense: SameSite=Lax/Strict\n  + explicit CSRF token (see CSRF skill)" },
        { term: "Cookie tossing", desc: "A sibling subdomain sets/overwrites your cookie", code: "Defense: narrow Domain, __Host- prefix" },
        { term: "XSS cookie theft", desc: "Injected script reads document.cookie", code: "Defense: HttpOnly (blocks it entirely)\n  + output encoding + CSP" },
        { term: "Stale session after logout", desc: "Old cookie value still works post-logout", code: "Defense: delete the STORE record on logout,\n  not just clear-cookie" },
        { term: "Insecure remember-me", desc: "One static long-lived secret = permanent backdoor if leaked", code: "Defense: selector/validator scheme,\n  rotate both on every use" },
        { term: "Constant-time compare", desc: "Avoid timing leaks when comparing secrets", code: "python: hmac.compare_digest(a, b)\nnode:   crypto.timingSafeEqual(a, b)" },
        { term: "Credential stuffing", desc: "Rapid automated login attempts", code: "Defense: rate-limit logins per IP/account\n  via Redis INCR + EXPIRE" },
      ],
    },
    {
      title: "Pitfalls & Gotchas",
      color: "rose",
      rows: [
        { term: "Data in the cookie value", desc: "Client can read/tamper with anything cookie-visible", code: "WRONG: user={id:1,role:'admin'}\nRIGHT: sessionId=<opaque id>" },
        { term: "In-memory store + load balancer", desc: "Users randomly 'logged out' across instances", code: "Fix: shared Redis store, no stickiness" },
        { term: "SameSite=None without Secure", desc: "Browsers reject the cookie outright", code: "WRONG: SameSite=None (no Secure)\nRIGHT: SameSite=None; Secure" },
        { term: "Forgetting trust proxy", desc: "req.secure wrong behind a reverse proxy/LB", code: "app.set('trust proxy', 1)  // Express" },
        { term: "Only idle timeout, no absolute", desc: "An active hijacked session never expires", code: "Set BOTH idle and absolute timeouts" },
        { term: "Broad Domain 'just in case'", desc: "Widens blast radius to every subdomain", code: "Prefer omitting Domain (exact host only)" },
        { term: "Logging raw session IDs", desc: "A log leak becomes a hijacking incident", code: "log.info('session', { idHash: hash(sid) })" },
        { term: "Session ID in the URL", desc: "Leaks via browser history, referrers, proxies", code: "Never: /page?sid=abc123" },
        { term: "No TTL on store keys", desc: "Store grows unbounded, memory pressure/OOM", code: "Always EXPIRE / EX on every session write" },
        { term: "Trusting SameSite alone", desc: "Edge cases still exist across browsers/scenarios", code: "Pair SameSite with an explicit CSRF token" },
      ],
    },
    {
      title: "Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "Redis session store wiring", desc: "connect-redis + express-session", code: "new RedisStore({ client: redisClient,\n  prefix: 'sess:' })" },
        { term: "Session secret", desc: "Signs the session-ID cookie — from a secrets manager", code: "secret: process.env.SESSION_SECRET" },
        { term: "resave / saveUninitialized", desc: "Avoid unnecessary store writes", code: "resave: false, saveUninitialized: false" },
        { term: "rolling: true", desc: "Refreshes idle-timeout clock on every request", code: "cookie: { maxAge: 1800000 }, rolling: true" },
        { term: "Redis latency check", desc: "First place to look when sessions feel slow", code: "redis-cli --latency -h your-redis-host" },
        { term: "Inspect a session directly", desc: "Debug what is actually stored", code: "redis-cli\n> GET sess:abc123\n> TTL sess:abc123" },
        { term: "Cookie vs JWT", desc: "Instant revocation vs stateless scaling", code: "Cookie: revocable, needs shared state\nJWT: stateless, hard to revoke early" },
        { term: "Sticky vs shared store", desc: "Shared Redis store is the scaling standard", code: "Avoid sticky sessions; prefer stateless\n  app tier + shared Redis" },
        { term: "Health check includes store", desc: "A dead Redis should mark the app unready", code: "GET /readyz -> ping Redis, fail if unreachable" },
        { term: "Related skills", desc: "Where sessions connect on this platform", code: "see: Redis, JWT, OAuth 2.0 / OIDC,\n  CSRF, RBAC, ABAC" },
      ],
    },
  ],
};

export default cookiesSessions;
