import type { CheatSheetData } from "./types";

const docker: CheatSheetData = {
  title: "The Ultimate Docker Cheat Sheet",
  subtitle: "Images & containers · Dockerfile · Compose · networking & volumes · security · production toolbelt",
  sections: [
    {
      title: "Core Concepts & CLI Basics",
      color: "violet",
      rows: [
        { term: "Image", desc: "Immutable, layered template — the blueprint", code: "docker images\ndocker pull python:3.12-slim\ndocker rmi myapp:1.0" },
        { term: "Container", desc: "A running (or stopped) instance of an image", code: "docker run python:3.12-slim echo hi\ndocker ps -a" },
        { term: "docker run", desc: "Create + start a container from an image", code: "docker run -d --name web -p 8000:8000 myapp:1.0\n-d: detached  --name: label  -p host:container" },
        { term: "docker build", desc: "Build an image from a Dockerfile", code: "docker build -t myapp:1.0 .\n-t: tag  .: build context (cwd)" },
        { term: "docker exec", desc: "Run a command inside a running container", code: "docker exec -it web bash\ndocker exec web env" },
        { term: "docker logs", desc: "View a container's stdout/stderr", code: "docker logs -f web\ndocker logs --tail 200 --since 10m web" },
        { term: "docker stop / rm", desc: "Graceful stop (SIGTERM then SIGKILL); remove", code: "docker stop web\ndocker rm web\ndocker rm -f web   # force stop + remove" },
        { term: "docker inspect", desc: "Full JSON detail: mounts, network, limits", code: "docker inspect web\ndocker inspect web --format '{{.State.ExitCode}}'" },
        { term: "docker stats", desc: "Live CPU / memory / network usage", code: "docker stats\ndocker stats --no-stream" },
        { term: "Namespaces", desc: "Kernel isolation: PID, net, mount, UTS, IPC, user", code: "Container sees its own PID 1,\nits own network interfaces,\nits own filesystem root" },
        { term: "cgroups", desc: "Kernel resource limiting: CPU, memory, I/O", code: "Enforces memory.max, cpu.max\nprevents noisy-neighbor problems" },
        { term: "Union filesystem", desc: "overlayfs stacks read-only layers + 1 writable layer", code: "Multiple containers share\nunderlying image layers on disk" },
        { term: "Container vs VM", desc: "Shared kernel + namespaces vs hypervisor + own kernel", code: "Container: ms startup, MB overhead\nVM: min startup, GB overhead" },
      ],
    },
    {
      title: "Dockerfile Instructions",
      color: "blue",
      rows: [
        { term: "FROM", desc: "Base image to build from; can repeat for multi-stage", code: "FROM python:3.12-slim AS builder\nFROM python:3.12-slim" },
        { term: "WORKDIR", desc: "Sets cwd for following instructions + runtime", code: "WORKDIR /app" },
        { term: "COPY", desc: "Copy files from build context into the image", code: "COPY requirements.txt .\nCOPY src/ src/\nCOPY --from=builder /app/.venv /app/.venv" },
        { term: "RUN", desc: "Execute a command at BUILD time; new layer each call", code: "RUN pip install --no-cache-dir -r requirements.txt" },
        { term: "ENV", desc: "Set a runtime environment variable in the image", code: "ENV PYTHONUNBUFFERED=1 NODE_ENV=production" },
        { term: "ARG", desc: "Build-time-only variable (not in the running container)", code: "ARG BUILD_VERSION=dev" },
        { term: "EXPOSE", desc: "Documents the listening port — does NOT publish it", code: "EXPOSE 8000\n# publishing needs: docker run -p 8000:8000" },
        { term: "USER", desc: "Drop root before RUN/CMD execute — non-root by default", code: "RUN useradd -m appuser\nUSER appuser" },
        { term: "CMD", desc: "Default command/args; fully or partially overridable", code: "CMD [\"python\", \"app.py\"]\ndocker run myimage python other.py  # replaces CMD" },
        { term: "ENTRYPOINT", desc: "Fixed executable; CMD becomes its default arguments", code: "ENTRYPOINT [\"python\", \"app.py\"]\nCMD [\"--port\", \"8000\"]" },
        { term: "HEALTHCHECK", desc: "Lets Docker tell 'running' apart from 'actually healthy'", code: "HEALTHCHECK --interval=30s --timeout=3s \\\n  CMD curl -f http://localhost:8000/healthz || exit 1" },
        { term: ".dockerignore", desc: "Excludes files from the build context", code: ".git\nnode_modules\n.venv\n*.env" },
        { term: "LABEL", desc: "Attach metadata to the image", code: "LABEL maintainer=\"team@example.com\"" },
      ],
    },
    {
      title: "Layers, Caching & Multi-Stage Builds",
      color: "emerald",
      rows: [
        { term: "Layer caching rule", desc: "A layer is reused only if it AND all before it are unchanged", code: "Order: least-changing first\n(deps) then most-changing last (source)" },
        { term: "Cache-friendly order", desc: "Copy manifests, install, THEN copy source", code: "COPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . ." },
        { term: "Cache-unfriendly order", desc: "Copying source first busts the install layer every build", code: "COPY . .                 # BAD\nRUN pip install -r requirements.txt" },
        { term: "docker history", desc: "Inspect each layer's size — find bloat", code: "docker history myapp:1.0" },
        { term: "Multi-stage build", desc: "Build in one stage, ship only the artifact in a clean stage", code: "FROM python:3.12-slim AS builder\nRUN uv sync --frozen --no-dev\nFROM python:3.12-slim\nCOPY --from=builder /app/.venv /app/.venv" },
        { term: "Why multi-stage", desc: "Smaller image + smaller attack surface, not just size", code: "No compilers, no build cache,\nno dev deps in the final image" },
        { term: "BuildKit cache mount", desc: "Persist a package cache across builds without baking it in", code: "RUN --mount=type=cache,target=/root/.cache/pip \\\n  pip install -r requirements.txt" },
        { term: "Base image choice", desc: "slim (glibc, safe default) vs alpine (musl, smaller) vs distroless (no shell)", code: "python:3.12-slim   ~130MB\npython:3.12        ~900MB+\ngcr.io/distroless/python3  smallest" },
        { term: "buildx multi-arch", desc: "One image manifest, multiple CPU architectures", code: "docker buildx build \\\n  --platform linux/amd64,linux/arm64 \\\n  -t myapp:1.4.2 --push ." },
        { term: "Image tagging", desc: "NEVER 'latest' in production — use immutable tags", code: "docker tag myapp:1.0 registry/myapp:sha-a1b2c3d\ndocker push registry/myapp:sha-a1b2c3d" },
      ],
    },
    {
      title: "Compose, Networking & Volumes",
      color: "amber",
      rows: [
        { term: "docker compose up", desc: "Start a full multi-service stack", code: "docker compose up -d\ndocker compose logs -f api\ndocker compose down          # keeps volumes\ndocker compose down -v       # deletes volumes" },
        { term: "Compose service", desc: "One entry per container in the local stack", code: "services:\n  api:\n    build: .\n    ports: [\"8000:8000\"]" },
        { term: "depends_on + healthcheck", desc: "Wait for a REAL dependency, not just container start", code: "depends_on:\n  db:\n    condition: service_healthy" },
        { term: "Named volume", desc: "Docker-managed storage — production default for persistence", code: "docker volume create pgdata\ndocker run -v pgdata:/var/lib/postgresql/data postgres:16" },
        { term: "Bind mount", desc: "Maps a host path in — great for local hot-reload, not prod", code: "docker run -v \"$(pwd)/src:/app/src\" myapp:1.0" },
        { term: "bridge network", desc: "Default isolated network; user-defined bridge gives name-DNS", code: "docker network create mynet\ndocker run --network mynet --name db postgres:16\n# other containers reach it at host 'db'" },
        { term: "host network", desc: "Container shares host's network stack directly, no mapping", code: "docker run --network host myapp:1.0" },
        { term: "none network", desc: "No networking at all — max isolation for pure compute", code: "docker run --network none myapp:1.0" },
        { term: "Registry push/pull", desc: "Distribute images via Docker Hub, ECR, GCR, ACR, private", code: "docker login registry.example.com\ndocker push registry/myapp:1.4.2\ndocker pull registry/myapp:1.4.2" },
        { term: "Reference stack pattern", desc: "app + Postgres + Redis mirrors most real backends", code: "services:\n  api: {build: ., depends_on: [db, cache]}\n  db: {image: postgres:16-alpine}\n  cache: {image: redis:7-alpine}" },
      ],
    },
    {
      title: "Pitfalls & Common Errors",
      color: "rose",
      rows: [
        { term: "Root by default", desc: "No USER instruction means the final process runs as root", code: "# BAD: no USER line\n# GOOD:\nRUN useradd -m appuser\nUSER appuser" },
        { term: "Secrets in ENV/ARG", desc: "Persist in layer history forever, even if 'removed' later", code: "# NEVER: ENV OPENAI_API_KEY=sk-...\n# Inject at runtime instead:\ndocker run -e OPENAI_API_KEY=\"$SECRET\" myapp" },
        { term: "EXPOSE isn't publish", desc: "EXPOSE is documentation only", code: "EXPOSE 8000   # does nothing alone\ndocker run -p 8000:8000 myapp   # this publishes it" },
        { term: "Binding to localhost", desc: "App must bind 0.0.0.0, not 127.0.0.1, inside the container", code: "uvicorn app:app --host 0.0.0.0 --port 8000" },
        { term: "Exited (137)", desc: "OOM-killed by the kernel, or stop-timeout SIGKILL", code: "docker stats mycontainer\ndocker inspect --format '{{.HostConfig.Memory}}' mycontainer" },
        { term: "No .dockerignore", desc: "Slow builds, risk of leaking .git/.env into an image layer", code: ".dockerignore:\n.git\n.env\n*.log\n__pycache__" },
        { term: "latest in production", desc: "Mutable tag — rollback and 'what's running' become guesses", code: "# BAD: image: myapp:latest\n# GOOD: image: myapp:sha-a1b2c3d" },
        { term: "Docker socket mount", desc: "Hands the container root-equivalent control of the HOST", code: "# DANGEROUS unless fully understood:\n-v /var/run/docker.sock:/var/run/docker.sock" },
        { term: "No resource limits", desc: "One container can starve every neighbor on the host", code: "docker run --memory=512m --cpus=0.5 myapp:1.0" },
        { term: "Data in writable layer", desc: "Disappears on docker rm — use a named volume instead", code: "docker rm web   # writable layer data is GONE\n# use: -v pgdata:/var/lib/postgresql/data" },
      ],
    },
    {
      title: "Security & Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "Non-root USER", desc: "Highest-impact, lowest-effort security default", code: "RUN useradd -m appuser\nUSER appuser" },
        { term: "Minimal base image", desc: "slim/alpine/distroless shrink the CVE surface", code: "FROM python:3.12-slim\nFROM gcr.io/distroless/python3" },
        { term: "Image scanning", desc: "Check for known CVEs before deploy, gate CI on severity", code: "trivy image myapp:1.0\ndocker scout cves myapp:1.0" },
        { term: "Read-only root fs", desc: "Stops an attacker persisting a modified binary", code: "docker run --read-only --tmpfs /tmp myapp:1.0" },
        { term: "Drop capabilities", desc: "Grant only what the process actually needs", code: "docker run --cap-drop=ALL \\\n  --cap-add=NET_BIND_SERVICE myapp:1.0" },
        { term: "Never --privileged", desc: "Disables almost all isolation — avoid outside narrow CI cases", code: "# avoid: docker run --privileged ..." },
        { term: "Resource limits", desc: "Memory/CPU caps prevent noisy-neighbor problems", code: "docker run --memory=512m --memory-swap=512m \\\n  --cpus=1.0 myapp:1.0" },
        { term: "HEALTHCHECK in prod", desc: "Distinguishes 'process alive' from 'app actually works'", code: "HEALTHCHECK --interval=30s --timeout=3s --retries=3 \\\n  CMD curl -f http://localhost:8000/healthz || exit 1" },
        { term: "Graceful shutdown", desc: "Handle SIGTERM: drain in-flight work, then exit", code: "Orchestrator sends SIGTERM,\nwaits a grace period, then SIGKILL" },
        { term: "Secrets management", desc: "Inject from a vault/orchestrator secret store, never bake in", code: "See the Secrets Management skill\nfor Vault / cloud secret manager patterns" },
        { term: "CI pipeline shape", desc: "lint -> build -> test -> scan -> tag(SHA) -> push -> deploy", code: "See the CI/CD and GitHub Actions skills\nfor the full pipeline wiring" },
        { term: "Where containers run", desc: "Orchestrators schedule across many hosts", code: "See Kubernetes, AWS (ECS/EKS),\nAzure (AKS), GCP (GKE/Cloud Run) skills" },
      ],
    },
  ],
};

export default docker;
