import type { CheatSheetData } from "./types";

const gcp: CheatSheetData = {
  title: "The Ultimate GCP Cheat Sheet",
  subtitle: "Projects & IAM · compute · storage & data · networking · production toolbelt",
  sections: [
    {
      title: "Projects, Config & IAM Basics",
      color: "violet",
      rows: [
        { term: "gcloud projects create", desc: "Create a new project — GCP's billing/IAM/isolation boundary", code: "gcloud projects create my-app-prod\ngcloud config set project my-app-prod" },
        { term: "gcloud config", desc: "Set active project, region, zone defaults", code: "gcloud config set project my-app-prod\ngcloud config set compute/region us-central1\ngcloud config set compute/zone us-central1-a" },
        { term: "gcloud services enable", desc: "APIs are off by default — enable only what you need", code: "gcloud services enable compute.googleapis.com\ngcloud services enable run.googleapis.com\ngcloud services list --enabled" },
        { term: "Resource hierarchy", desc: "IAM policy inherits downward through this chain", code: "Organization\n  -> Folder\n      -> Project\n          -> Resource" },
        { term: "IAM binding", desc: "Grant a role to a member on a resource", code: "gcloud projects add-iam-policy-binding my-app-prod \\\n  --member=user:jane@example.com \\\n  --role=roles/cloudsql.client" },
        { term: "Service account", desc: "An identity for workloads, not humans", code: "gcloud iam service-accounts create app \\\n  --display-name=\"App backend\"" },
        { term: "Least privilege rule", desc: "Never grant Owner/Editor to a workload", code: "roles/editor        # WRONG for a workload\nroles/cloudsql.client  # RIGHT: narrow, specific" },
        { term: "Custom roles", desc: "Assemble an exact permission set when predefined roles are too broad", code: "gcloud iam roles create appReadOnlyDb \\\n  --project=my-app-prod \\\n  --permissions=cloudsql.instances.get,cloudsql.instances.list" },
        { term: "Organization Policy", desc: "Hard constraints, separate system from IAM grants", code: "constraints/storage.publicAccessPrevention\nconstraints/compute.vmExternalIpAccess" },
        { term: "gcloud auth", desc: "Authenticate the CLI / app default credentials", code: "gcloud auth login\ngcloud auth application-default login" },
        { term: "IAM Policy Troubleshooter", desc: "Answers why an identity can/can't access a resource", code: "gcloud policy-intelligence query-activity \\\n  --activity-type=serviceAccountLastAuthentication" },
        { term: "Budget alerts", desc: "Set from day one — avoid invoice-shock", code: "Billing console -> Budgets & alerts\n-> set threshold % of monthly budget" },
      ],
    },
    {
      title: "Compute: Engine, Run, Functions, GKE",
      color: "blue",
      rows: [
        { term: "Compute Engine VM", desc: "Full VM control, any OS/runtime", code: "gcloud compute instances create web-1 \\\n  --zone=us-central1-a --machine-type=e2-medium \\\n  --image-family=debian-12 --image-project=debian-cloud" },
        { term: "Cloud Run deploy", desc: "Serverless containers, scale to zero", code: "gcloud run deploy api --source=. \\\n  --region=us-central1 \\\n  --service-account=app@proj.iam.gserviceaccount.com" },
        { term: "Cloud Run scaling knobs", desc: "Avoid cold starts vs pay for idle", code: "--min-instances=1 --max-instances=20\n--memory=512Mi --cpu=1 --timeout=30s" },
        { term: "Cloud Run traffic split", desc: "Canary rollout between revisions", code: "gcloud run services update-traffic api \\\n  --to-revisions=api-v2=10,api-v1=90" },
        { term: "Cloud Functions", desc: "Single-purpose, event-triggered serverless", code: "gcloud functions deploy processUpload \\\n  --runtime=python312 --trigger-bucket=my-uploads" },
        { term: "GKE Autopilot", desc: "Google manages nodes; pay per pod resource request", code: "gcloud container clusters create-auto app-cluster \\\n  --region=us-central1" },
        { term: "GKE Standard", desc: "You manage node pools; full customization", code: "gcloud container clusters create app-cluster \\\n  --num-nodes=3 --machine-type=e2-standard-4" },
        { term: "kubectl basics", desc: "Interact with a GKE cluster", code: "kubectl get pods\nkubectl describe pod POD_NAME\nkubectl logs POD_NAME" },
        { term: "Compute decision rule", desc: "Match workload shape to service", code: "Spiky HTTP API      -> Cloud Run\nSingle event trigger -> Cloud Functions\nComplex orchestration -> GKE\nFull OS control       -> Compute Engine" },
        { term: "Preemptible / Spot VM", desc: "Cheap, interruptible compute for batch jobs", code: "gcloud compute instances create batch-1 \\\n  --provisioning-model=SPOT --instance-termination-action=STOP" },
      ],
    },
    {
      title: "Storage & Data Services",
      color: "emerald",
      rows: [
        { term: "Cloud Storage bucket", desc: "Object storage — globally unique bucket names", code: "gcloud storage buckets create gs://my-assets \\\n  --location=us-central1" },
        { term: "Upload / list objects", desc: "Basic Cloud Storage operations", code: "gcloud storage cp ./file.png gs://my-assets/\ngcloud storage ls gs://my-assets/" },
        { term: "Uniform bucket-level access", desc: "Prevent accidental per-object public ACLs", code: "gcloud storage buckets update gs://my-assets \\\n  --uniform-bucket-level-access" },
        { term: "Persistent Disk", desc: "Block storage attached to a Compute Engine VM", code: "gcloud compute disks create data-disk \\\n  --size=100GB --zone=us-central1-a --type=pd-ssd" },
        { term: "Cloud SQL instance", desc: "Managed Postgres/MySQL/SQL Server, regional", code: "gcloud sql instances create app-db \\\n  --database-version=POSTGRES_15 \\\n  --tier=db-custom-2-7680 --availability-type=REGIONAL" },
        { term: "Cloud SQL private IP rule", desc: "Never expose a production database publicly", code: "--no-assign-ip  # use Auth Proxy or VPC connector instead" },
        { term: "Firestore", desc: "Serverless NoSQL document store, offline sync", code: "gcloud firestore databases create --location=nam5" },
        { term: "BigQuery query", desc: "Serverless SQL warehouse, billed by bytes scanned", code: "bq query --use_legacy_sql=false \\\n  'SELECT COUNT(*) FROM ds.tbl WHERE _PARTITIONDATE=CURRENT_DATE()'" },
        { term: "BigQuery partitioning", desc: "The single biggest cost/performance lever", code: "CREATE TABLE ds.events\nPARTITION BY DATE(created_at)\nCLUSTER BY user_id AS SELECT * FROM staging.events" },
        { term: "BigQuery ML", desc: "Train models directly with SQL, no data export", code: "CREATE MODEL ds.churn_model\nOPTIONS(model_type='logistic_reg') AS\nSELECT * FROM ds.training_data" },
        { term: "Cloud Spanner", desc: "Globally distributed, strongly consistent relational DB", code: "gcloud spanner instances create app-spanner \\\n  --config=regional-us-central1 --nodes=1" },
        { term: "Vertex AI", desc: "Unified ML platform: training, tuning, prediction, Gemini", code: "gcloud ai models upload --region=us-central1 \\\n  --display-name=my-model --container-image-uri=IMAGE_URI" },
      ],
    },
    {
      title: "Networking",
      color: "amber",
      rows: [
        { term: "Custom VPC", desc: "Global by default — one VPC spans every region", code: "gcloud compute networks create app-vpc \\\n  --subnet-mode=custom" },
        { term: "Subnet", desc: "Region-scoped IP range inside the global VPC", code: "gcloud compute networks subnets create app-subnet \\\n  --network=app-vpc --region=us-central1 --range=10.0.0.0/20" },
        { term: "Firewall rule", desc: "Deny-by-default ingress except explicit allows", code: "gcloud compute firewall-rules create allow-http \\\n  --network=app-vpc --allow=tcp:80,tcp:443 \\\n  --source-ranges=0.0.0.0/0 --target-tags=web" },
        { term: "Serverless VPC Access connector", desc: "Lets Cloud Run/Functions reach private VPC resources", code: "gcloud compute networks vpc-access connectors create app-conn \\\n  --network=app-vpc --region=us-central1 --range=10.8.0.0/28" },
        { term: "Cloud SQL Auth Proxy", desc: "Encrypted, IAM-authenticated DB connection, no public IP", code: "cloud-sql-proxy my-app-prod:us-central1:app-db \\\n  --port=5432" },
        { term: "Global HTTPS Load Balancer", desc: "One anycast IP fronting multi-region backends", code: "gcloud compute backend-services create api-backend \\\n  --global --protocol=HTTPS" },
        { term: "Cloud CDN", desc: "Edge caching in front of Cloud Storage/load balancer", code: "gcloud compute backend-buckets create static-cdn \\\n  --gcs-bucket-name=my-assets --enable-cdn" },
        { term: "DNS", desc: "Managed DNS zones for custom domains", code: "gcloud dns managed-zones create app-zone \\\n  --dns-name=example.com. --description=\"App DNS\"" },
        { term: "VPC Service Controls", desc: "Perimeter blocking data exfiltration outside allowed networks", code: "gcloud access-context-manager perimeters create app-perimeter \\\n  --resources=projects/123456 --restricted-services=bigquery.googleapis.com" },
      ],
    },
    {
      title: "Security, Pitfalls & Shared Responsibility",
      color: "rose",
      rows: [
        { term: "Shared responsibility split", desc: "Google secures the platform; you secure your config", code: "Google: hypervisor, data centers, network hardware\nYou: IAM, firewall rules, app code, data classification" },
        { term: "Public bucket pitfall", desc: "The classic real-world breach pattern", code: "# WRONG: --member=allUsers --role=roles/storage.objectViewer\n# Audit with Security Command Center instead" },
        { term: "Overly broad IAM pitfall", desc: "Editor/Owner on a service account = huge blast radius", code: "# WRONG: roles/editor on a workload SA\n# RIGHT: exactly the predefined roles it needs" },
        { term: "Service account key sprawl", desc: "Long-lived JSON keys don't expire — prefer alternatives", code: "# Prefer attached SAs (GCP-native compute) or\n# Workload Identity Federation (external workloads)" },
        { term: "Missing regional redundancy", desc: "Single-zone deploys risk full outages", code: "--availability-type=REGIONAL   # Cloud SQL\nmulti-zone node pools           # GKE" },
        { term: "Secret Manager", desc: "Never hardcode credentials in code or images", code: "gcloud secrets create db-password --data-file=pw.txt\ngcloud secrets versions access latest --secret=db-password" },
        { term: "CMEK (Cloud KMS)", desc: "Customer-managed encryption keys for regulated data", code: "gcloud kms keys create app-key \\\n  --keyring=app-ring --location=us-central1 --purpose=encryption" },
        { term: "Audit logs", desc: "Admin Activity is free/default; Data Access must be enabled", code: "gcloud logging read \\\n  'logName=\"projects/P/logs/cloudaudit.googleapis.com%2Fdata_access\"'" },
        { term: "SQL injection rule", desc: "Same as any platform — always parameterize", code: "cursor.execute('SELECT * FROM users WHERE id=%s', (uid,))" },
        { term: "shell=True pitfall", desc: "Same as any platform — never pass user input to a shell", code: "subprocess.run([cmd, arg])   # RIGHT\n# subprocess.run(cmd, shell=True)  # WRONG with user input" },
      ],
    },
    {
      title: "Production Toolbelt & Terminology Map",
      color: "cyan",
      rows: [
        { term: "Cloud Logging query", desc: "Structured log search across every service", code: "gcloud logging read \\\n  'resource.type=\"cloud_run_revision\" AND severity>=ERROR' \\\n  --limit=50" },
        { term: "Cloud Monitoring alert", desc: "Fire when p99 latency crosses a threshold", code: "gcloud alpha monitoring policies create \\\n  --notification-channels=CH_ID \\\n  --condition-threshold-value=2000 --condition-threshold-duration=300s" },
        { term: "Cloud Trace", desc: "Per-request latency waterfall across service hops", code: "gcloud trace list-traces --project=my-app-prod" },
        { term: "Cloud Build (CI/CD)", desc: "Native build/test/deploy pipeline", code: "gcloud builds submit --tag \\\n  us-central1-docker.pkg.dev/proj/app/api:v1" },
        { term: "Terraform basics", desc: "Provision infra as code, not console clicks", code: "terraform init\nterraform plan -out=tfplan\nterraform apply tfplan" },
        { term: "Sustained use discount", desc: "Automatic discount for steady-state Compute Engine usage", code: "Applies automatically -- no commitment needed" },
        { term: "Committed use discount", desc: "Upfront 1yr/3yr commitment for predictable workloads", code: "gcloud compute commitments create cud-1 \\\n  --plan=twelve-month --region=us-central1" },
        { term: "Preemptible/Spot pricing", desc: "Deep discounts for interruptible batch/training jobs", code: "--provisioning-model=SPOT   # up to significant savings vs on-demand" },
        { term: "Health endpoints", desc: "Wire into GKE probes / Cloud Run startup checks", code: "/healthz  -> liveness (process up)\n/readyz   -> readiness (dependencies reachable)" },
        { term: "Compute Engine <-> AWS/Azure", desc: "Terminology map: compute", code: "GCP: Compute Engine\nAWS: EC2\nAzure: Virtual Machines" },
        { term: "Cloud Storage <-> AWS/Azure", desc: "Terminology map: object storage", code: "GCP: Cloud Storage\nAWS: S3\nAzure: Blob Storage" },
        { term: "Cloud SQL <-> AWS/Azure", desc: "Terminology map: managed relational DB", code: "GCP: Cloud SQL\nAWS: RDS\nAzure: SQL Database" },
        { term: "IAM <-> AWS/Azure", desc: "Terminology map: identity and access", code: "GCP: IAM\nAWS: IAM\nAzure: RBAC (Azure AD)" },
        { term: "VPC <-> AWS/Azure", desc: "Terminology map: virtual network", code: "GCP: VPC (global)\nAWS: VPC (regional)\nAzure: VNet (regional)" },
        { term: "GKE <-> AWS/Azure", desc: "Terminology map: managed Kubernetes", code: "GCP: GKE\nAWS: EKS\nAzure: AKS" },
      ],
    },
  ],
};

export default gcp;
