import type { CheatSheetData } from "./types";

const git: CheatSheetData = {
  title: "The Ultimate Git Cheat Sheet",
  subtitle: "Object model · three trees · branching · merge vs rebase · recovery · production toolbelt",
  sections: [
    {
      title: "Setup & Core Commands",
      color: "violet",
      rows: [
        { term: "git init", desc: "Create a new repository in the current directory", code: "git init\nls -a   # note the new .git/ directory" },
        { term: "git clone", desc: "Copy an existing repository with its full history", code: "git clone https://github.com/org/repo.git\ngit clone --depth 1 <url>   # shallow, CI-friendly" },
        { term: "git config", desc: "Set identity and global behavior once per machine", code: "git config --global user.name 'Ada'\ngit config --global user.email 'ada@example.com'\ngit config --global init.defaultBranch main" },
        { term: "git status", desc: "Show branch, staged/unstaged changes, conflicts — run this first, always", code: "git status" },
        { term: "git add", desc: "Working directory to staging area (index)", code: "git add file.py\ngit add .\ngit add -p   # interactively choose hunks" },
        { term: "git commit", desc: "Staging area to repository — a new snapshot", code: "git commit -m 'Add pricing module'\ngit commit --amend -m 'Fix message'  # rewrite LAST commit only" },
        { term: "git restore", desc: "Discard working-dir changes or unstage a file", code: "git restore file.py             # discard edits\ngit restore --staged file.py    # unstage, keep edits" },
        { term: "git diff", desc: "Show exact changes at each stage", code: "git diff             # unstaged vs index\ngit diff --staged    # staged vs last commit\ngit show HEAD         # diff introduced by a commit" },
        { term: "git log", desc: "Browse commit history", code: "git log --oneline --graph --all\ngit log -S'text' -- path/   # pickaxe: find commits changing this string" },
      ],
    },
    {
      title: "The Object Model (Core Data Structures)",
      color: "blue",
      rows: [
        { term: "Blob", desc: "Raw file content, hashed by type+length header plus bytes — no filename attached", code: "echo -n 'hello world' | git hash-object --stdin\n# 95d09f2b10159347eece71399a7e2e907ea3df4" },
        { term: "Tree", desc: "A directory listing: mode, type, SHA, name entries pointing to blobs/subtrees", code: "git cat-file -p HEAD^{tree}" },
        { term: "Commit", desc: "Points to one tree, zero+ parents, author/committer/message — hashed the same way", code: "git cat-file -p HEAD\n# tree <sha>\n# parent <sha>\n# author ...\n#\n# message" },
        { term: "Ref", desc: "A branch/tag name — just a text file containing one commit SHA", code: "cat .git/refs/heads/main\ngit rev-parse main" },
        { term: "HEAD", desc: "Pointer to where you currently are — usually points AT a branch", code: "cat .git/HEAD\n# ref: refs/heads/main" },
        { term: "Content-addressing", desc: "Identical content anywhere hashes identically and is stored once", code: "git hash-object --stdin < file1.txt\ngit hash-object --stdin < file2.txt  # same content, same SHA" },
        { term: "git cat-file", desc: "Inspect any object's raw type/content by SHA", code: "git cat-file -t <sha>   # type\ngit cat-file -p <sha>   # pretty-print content" },
        { term: "Loose vs packed objects", desc: "Individual files under .git/objects, later compressed into packfiles", code: "git count-objects -v -H\ngit gc   # pack and prune unreachable objects" },
      ],
    },
    {
      title: "Three Trees & Everyday Idioms",
      color: "emerald",
      rows: [
        { term: "Working directory", desc: "The files you actually edit on disk", code: "vim pricing.py" },
        { term: "Staging area / index", desc: "What will go into the NEXT commit — a single file, .git/index", code: "git add pricing.py   # snapshot into the index" },
        { term: "Repository / HEAD", desc: "Permanent, content-addressed history once committed", code: "git commit -m 'msg'   # index -> repository" },
        { term: "Branch = pointer", desc: "NOT a copy of files — a 41-byte ref to one commit", code: "git branch feature/x   # writes one small file\ngit switch feature/x   # moves HEAD to point there" },
        { term: "git switch / git restore", desc: "Modern, focused replacements for overloaded checkout", code: "git switch -c feature/signup   # create + switch\ngit restore file.py             # discard edits" },
        { term: "Detached HEAD", desc: "HEAD points straight at a commit, no branch tracking it", code: "git checkout <sha>\ngit branch rescue-me   # save any new commits before switching away!" },
        { term: "Fast-forward merge", desc: "Target hasn't moved — pointer just slides forward, no new commit", code: "git switch main\ngit merge feature/x   # FF if main unchanged since branch" },
        { term: "True (3-way) merge", desc: "Both branches moved — creates a 2-parent merge commit", code: "git merge feature/x\n# Merge commit created" },
        { term: "Conflict resolution", desc: "Edit out the markers, keep the correct final content", code: "<<<<<<< HEAD\nrate = 0.10\n=======\nrate = 0.15\n>>>>>>> feature/pricing\n# fix, then: git add file && git commit" },
        { term: "git stash", desc: "Shelve uncommitted work to get a clean working directory", code: "git stash\ngit stash -u        # include untracked files\ngit stash pop       # reapply and remove\ngit stash list" },
        { term: "git cherry-pick", desc: "Apply one specific commit onto the current branch", code: "git cherry-pick <sha>\ngit cherry-pick <sha> --no-commit  # review first" },
        { term: "Tags: lightweight vs annotated", desc: "Annotated = full object with message/author/signature; preferred for releases", code: "git tag v1.0                         # lightweight\ngit tag -a v1.0 -m 'Release 1.0'     # annotated\ngit push origin v1.0                 # tags don't auto-push" },
        { term: ".gitignore", desc: "Prevents NEW untracked files from being staged (not already-tracked ones)", code: "printf '*.env\\n.venv/\\n__pycache__/\\n' > .gitignore\ngit rm --cached file  # untrack without deleting" },
      ],
    },
    {
      title: "Merge, Rebase & History Power Features",
      color: "amber",
      rows: [
        { term: "git merge", desc: "Combine histories, preserving true (parallel) chronology", code: "git switch main\ngit merge feature/login" },
        { term: "git rebase", desc: "Replay commits onto a new base — new SHAs, linear history", code: "git switch feature/login\ngit rebase main" },
        { term: "Interactive rebase", desc: "Squash, reword, drop, or reorder commits before they're shared", code: "git rebase -i HEAD~4\n# pick / squash / fixup / reword / drop" },
        { term: "The hard rule", desc: "Never rebase commits already pushed and possibly pulled by others", code: "# Safe: rebase local, unpushed commits only\n# Unsafe: rebase + force-push a branch others have" },
        { term: "git rebase/merge --abort", desc: "Bail out cleanly from a bad conflict resolution", code: "git rebase --abort\ngit merge --abort" },
        { term: "git bisect", desc: "Binary-search a regression — O(log n) tests among n commits", code: "git bisect start\ngit bisect bad\ngit bisect good v1.2.0\ngit bisect run pytest tests/test_x.py\ngit bisect reset" },
        { term: "git reflog", desc: "Local safety net — recovers commits no branch/tag points to anymore", code: "git reflog\ngit branch rescue <sha-from-reflog>" },
        { term: "git revert", desc: "Safe undo on SHARED branches — adds a new commit reversing one", code: "git revert <sha>" },
        { term: "git reset (soft/mixed/hard)", desc: "Moves the branch pointer — can discard commits; LOCAL branches only", code: "git reset --soft HEAD~1    # keep changes staged\ngit reset --mixed HEAD~1   # keep changes, unstaged\ngit reset --hard HEAD~1    # discard everything" },
        { term: "git blame", desc: "Find which commit last touched each line", code: "git blame -L 10,30 -- pricing.py" },
        { term: "git worktree", desc: "A second working directory from the SAME repo, no re-clone", code: "git worktree add ../hotfix main" },
        { term: "git filter-repo", desc: "Rewrite ALL of history — e.g. purge a committed secret", code: "git filter-repo --path secrets.json --invert-paths\n# then: rotate the credential + force-push + team re-clones" },
      ],
    },
    {
      title: "Pitfalls & Gotchas",
      color: "rose",
      rows: [
        { term: "Committed secrets", desc: "A pushed secret is compromised THE MOMENT it's pushed — rewriting history alone doesn't un-leak it", code: "# 1. Rotate the credential immediately\n# 2. git filter-repo to purge from history\n# 3. Force-push + everyone re-clones/hard-resets" },
        { term: ".gitignore doesn't retroact", desc: "Only blocks NEW untracked files — already-committed files need explicit removal", code: "git rm --cached leaked-file.txt\n# still need filter-repo if it was ever pushed" },
        { term: "Force-push without --force-with-lease", desc: "Plain --force can silently discard a teammate's just-pushed commits", code: "git push --force-with-lease origin my-branch  # refuses if remote moved" },
        { term: "Rebasing shared history", desc: "New SHAs for every rebased commit — breaks anyone who already pulled the old ones", code: "# Only rebase commits that exist ONLY on your local, unpushed branch" },
        { term: "Fast-forward confusion", desc: "Why some merges make a merge commit and others silently don't", code: "# FF: target branch unchanged since divergence -> pointer just moves\n# Non-FF: both moved -> real 2-parent merge commit" },
        { term: "Blind conflict resolution", desc: "Picking 'ours'/'theirs' without reading both sides discards real work", code: "git checkout --ours file.py   # use with care, read the diff first\ngit checkout --theirs file.py" },
        { term: "revert vs reset", desc: "revert = safe, new commit, shared-branch friendly. reset = moves pointer, can discard commits", code: "git revert <sha>       # safe on shared branches\ngit reset --hard <sha> # local/private branches ONLY" },
        { term: "Large binaries committed raw", desc: "Bloats every clone FOREVER, even after later deletion, unless history is rewritten", code: "git lfs install\ngit lfs track '*.safetensors'\ngit add .gitattributes" },
        { term: "'refusing to merge unrelated histories'", desc: "Two branches/repos share no common ancestor commit", code: "git merge --allow-unrelated-histories  # only if genuinely intended" },
        { term: "Detached HEAD data loss", desc: "Commits made here vanish from view (not disk) once you switch away without a branch", code: "git branch rescue-name   # BEFORE switching away" },
      ],
    },
    {
      title: "Remotes & Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "git remote", desc: "List/manage connections to other full copies of the repo", code: "git remote -v\ngit remote add origin <url>" },
        { term: "git fetch", desc: "Download new commits/branches — never touches your working directory", code: "git fetch origin\ngit fetch --prune   # also remove local refs for deleted remote branches" },
        { term: "git pull", desc: "fetch + merge (or rebase, if configured) into your current branch", code: "git pull\ngit pull --rebase   # keeps YOUR branch history linear" },
        { term: "git push", desc: "Upload commits/tags; rejected if remote has diverged (non-fast-forward)", code: "git push origin feature/login\ngit push origin --tags" },
        { term: "Branch protection (platform)", desc: "Require passing CI + review before merge to main — not Git core, hosting-platform feature", code: "# GitHub/GitLab settings: required status checks,\n# required reviewers, no direct pushes to main" },
        { term: "Git hooks", desc: "Local automation points — NOT cloned with the repo by default", code: "# .git/hooks/pre-commit\n#!/bin/sh\nruff check . || exit 1" },
        { term: "pre-commit framework", desc: "Standard way to share hook configuration across a team", code: "pre-commit install\npre-commit run --all-files" },
        { term: "Signed commits", desc: "Cryptographic provenance for supply-chain-conscious teams", code: "git config --global commit.gpgsign true\ngit commit -S -m 'Signed release commit'" },
        { term: "Trunk-based development", desc: "One trunk, short-lived branches, frequent integration — needs strong CI/CD", code: "main (always releasable)\n  + feature/x (hours-2 days, merged, deleted)" },
        { term: "Git Flow", desc: "Long-lived develop/release/hotfix branches — suits infrequent versioned releases", code: "main <- release/1.2 <- develop <- feature/x\nhotfix/urgent -> main + develop" },
        { term: "Shallow / partial clone", desc: "Faster CI checkouts and huge-monorepo dev clones", code: "git clone --depth 1 <url>\ngit clone --filter=blob:none <url>\ngit sparse-checkout set path/" },
        { term: "Repo health check", desc: "Spot unexpected growth (often an accidentally committed binary)", code: "git count-objects -v -H\ndu -sh .git/" },
      ],
    },
  ],
};

export default git;
