import type { CheatSheetData } from "./types";

const githubActions: CheatSheetData = {
  title: "The Ultimate GitHub Actions Cheat Sheet",
  subtitle: "Workflow syntax · runners · caching & reuse · security · production deploys",
  sections: [
    {
      title: "Workflow Structure & Triggers",
      color: "violet",
      rows: [
        { term: "File location", desc: "Every workflow is a YAML file here", code: ".github/workflows/ci.yml\n.github/workflows/deploy.yml" },
        { term: "name", desc: "Human-readable label shown in the Actions tab", code: "name: CI" },
        { term: "on: push", desc: "Run on commits to matching branches", code: "on:\n  push:\n    branches: [main, \"release/*\"]" },
        { term: "on: pull_request", desc: "Run on PR open/update; safe default for fork code (read-only token, no secrets)", code: "on:\n  pull_request:\n    branches: [main]" },
        { term: "on: schedule", desc: "Cron-based trigger, always UTC", code: "on:\n  schedule:\n    - cron: \"0 3 * * *\"" },
        { term: "on: workflow_dispatch", desc: "Manual trigger with a Run workflow button + inputs", code: "on:\n  workflow_dispatch:\n    inputs:\n      environment:\n        required: true" },
        { term: "on: workflow_call", desc: "Marks this workflow as reusable from another repo", code: "on:\n  workflow_call:\n    inputs:\n      environment: { required: true, type: string }" },
        { term: "path filters", desc: "Skip runs for unrelated changes (monorepos)", code: "on:\n  push:\n    paths:\n      - \"services/api/**\"" },
        { term: "jobs", desc: "Independent units of work; parallel by default", code: "jobs:\n  test:\n    runs-on: ubuntu-latest\n    steps: [...]" },
        { term: "runs-on", desc: "Which runner OS/image executes the job", code: "runs-on: ubuntu-latest\nruns-on: windows-latest\nruns-on: macos-latest\nruns-on: self-hosted" },
        { term: "timeout-minutes", desc: "Hard cap so a hung job doesn't burn minutes forever", code: "jobs:\n  test:\n    timeout-minutes: 10" },
        { term: "permissions", desc: "Least-privilege GITHUB_TOKEN scope, top-level or per-job", code: "permissions:\n  contents: read\njobs:\n  release:\n    permissions:\n      contents: write" },
      ],
    },
    {
      title: "Steps, Actions & Contexts",
      color: "blue",
      rows: [
        { term: "run:", desc: "Execute a shell command directly", code: "steps:\n  - run: pytest -q" },
        { term: "uses:", desc: "Invoke a reusable action (Marketplace, local, or another repo)", code: "steps:\n  - uses: actions/checkout@v4" },
        { term: "with:", desc: "Pass inputs to an action", code: "- uses: actions/setup-python@v5\n  with:\n    python-version: \"3.12\"" },
        { term: "actions/checkout", desc: "Near-universal first step — pulls repo files onto the runner", code: "- uses: actions/checkout@v4\n  with:\n    fetch-depth: 0" },
        { term: "setup-language actions", desc: "Install and cache a language runtime", code: "- uses: actions/setup-python@v5\n  with: { python-version: \"3.12\", cache: \"pip\" }\n- uses: actions/setup-node@v4" },
        { term: "SHA-pinning (security)", desc: "Pin sensitive third-party actions to a commit, not a tag", code: "- uses: some/action@a1b2c3d4e5f6...   # v2.3.1" },
        { term: "github context", desc: "Event, repo, commit, actor metadata", code: "echo commit \\${{ github.sha }}\necho branch \\${{ github.ref_name }}\necho repo \\${{ github.repository }}" },
        { term: "secrets context", desc: "Encrypted secret values; auto-masked in logs", code: "password: \\${{ secrets.GITHUB_TOKEN }}\ntoken: \\${{ secrets.PROD_DEPLOY_TOKEN }}" },
        { term: "matrix context", desc: "Current combination inside a matrix build", code: "python-version: \\${{ matrix.python-version }}" },
        { term: "needs context", desc: "Read an upstream job's declared output", code: "echo \\${{ needs.build.outputs.image_tag }}" },
        { term: "steps context", desc: "Read an earlier step's output in the same job", code: "echo \\${{ steps.tag.outputs.tag }}" },
        { term: "Step + job outputs", desc: "Expose a value for later steps/jobs", code: "- id: tag\n  run: echo \"tag=$(git rev-parse --short HEAD)\" >> \"$GITHUB_OUTPUT\"\njobs:\n  build:\n    outputs:\n      image_tag: \\${{ steps.tag.outputs.tag }}" },
      ],
    },
    {
      title: "Jobs, Matrix & Artifacts",
      color: "emerald",
      rows: [
        { term: "needs:", desc: "Declare a job dependency — turns parallel jobs into a DAG", code: "jobs:\n  deploy:\n    needs: [build, test]" },
        { term: "strategy.matrix", desc: "Fan one job out across a Cartesian product of variables", code: "strategy:\n  matrix:\n    os: [ubuntu-latest, windows-latest]\n    python-version: [\"3.11\", \"3.12\"]" },
        { term: "fail-fast: false", desc: "Let every matrix combination finish even if one fails", code: "strategy:\n  matrix: { ... }\n  fail-fast: false" },
        { term: "matrix include/exclude", desc: "Add or remove specific combinations without a full Cartesian product", code: "strategy:\n  matrix:\n    include:\n      - os: windows-latest\n        experimental: true" },
        { term: "actions/upload-artifact", desc: "Persist a file for download or a later job", code: "- uses: actions/upload-artifact@v4\n  with:\n    name: coverage-report\n    path: coverage.xml" },
        { term: "actions/download-artifact", desc: "Pull an uploaded artifact into another job", code: "- uses: actions/download-artifact@v4\n  with:\n    name: coverage-report" },
        { term: "if: conditions", desc: "Run a step/job conditionally", code: "- run: notify_failure.sh\n  if: failure()\n- run: cleanup.sh\n  if: always()" },
        { term: "docker/build-push-action", desc: "Build and push an image, tag with the immutable commit SHA", code: "- uses: docker/build-push-action@v6\n  with:\n    push: true\n    tags: ghcr.io/org/app:\\${{ github.sha }}" },
      ],
    },
    {
      title: "Caching, Reuse & Concurrency",
      color: "amber",
      rows: [
        { term: "actions/cache", desc: "Speed up installs; key on a lockfile hash", code: "- uses: actions/cache@v4\n  with:\n    path: ~/.cache/pip\n    key: pip-\\${{ runner.os }}-\\${{ hashFiles('requirements.txt') }}" },
        { term: "restore-keys", desc: "Fallback partial-match cache when the exact key misses", code: "restore-keys: |\n  pip-\\${{ runner.os }}-" },
        { term: "cache-hit-rate", desc: "Track it — a low hit rate wastes real billed minutes on every run", code: "# a matching lockfile hash across runs = cache hit\n# a changed lockfile = correctly invalidated" },
        { term: "Composite action", desc: "Dedupe steps within one repo (runs inside the caller's job)", code: "# .github/actions/setup/action.yml\nruns:\n  using: composite\n  steps:\n    - run: pip install -r requirements.txt\n      shell: bash" },
        { term: "Use a composite action", desc: "Reference it by local path", code: "- uses: ./.github/actions/setup" },
        { term: "Reusable workflow (callee)", desc: "Dedupe whole pipelines across many repos", code: "on:\n  workflow_call:\n    inputs:\n      environment: { required: true, type: string }\n    secrets:\n      DEPLOY_TOKEN: { required: true }" },
        { term: "Reusable workflow (caller)", desc: "Invoke a shared pipeline, versioned", code: "jobs:\n  call-deploy:\n    uses: org/shared/.github/workflows/deploy.yml@v1\n    with: { environment: production }\n    secrets:\n      DEPLOY_TOKEN: \\${{ secrets.PROD_TOKEN }}" },
        { term: "concurrency group", desc: "Cancel a stale run when a newer commit lands on the same ref", code: "concurrency:\n  group: ci-\\${{ github.workflow }}-\\${{ github.ref }}\n  cancel-in-progress: true" },
        { term: "Never cancel prod deploys", desc: "Disable cancellation for the production-deploy workflow", code: "concurrency:\n  group: deploy-\\${{ github.ref }}\n  cancel-in-progress: false" },
      ],
    },
    {
      title: "Security Pitfalls",
      color: "rose",
      rows: [
        { term: "pull_request vs pull_request_target", desc: "pull_request: read-only token, no secrets for fork PRs (safe). pull_request_target: write token + secrets on an untrusted event (risky)", code: "on: pull_request        # safe default for fork code\non: pull_request_target # only for metadata tasks; never checkout fork code" },
        { term: "The privilege-escalation trap", desc: "Never checkout + execute a fork's ref inside pull_request_target", code: "# DANGEROUS inside pull_request_target:\n- uses: actions/checkout@v4\n  with:\n    ref: \\${{ github.event.pull_request.head.sha }}\n- run: npm install && npm test   # runs fork code WITH secrets" },
        { term: "SHA-pin third-party actions", desc: "A tag is mutable and can be repointed; a commit SHA cannot", code: "- uses: some/action@a1b2c3d4...   # not @v2" },
        { term: "Least-privilege GITHUB_TOKEN", desc: "Default to read-only; escalate only the job that needs more", code: "permissions:\n  contents: read\njobs:\n  release:\n    permissions:\n      contents: write" },
        { term: "Never print secrets", desc: "GitHub masks known secret values, but a transformed copy still leaks", code: "# WRONG: echo the base64 of a secret and it may bypass masking\n# RIGHT: never manipulate-then-print a secret value" },
        { term: "Environment protection rules", desc: "Require human reviewer approval before a job runs", code: "jobs:\n  deploy:\n    environment: production   # configured in Settings > Environments" },
        { term: "Environment-scoped secrets", desc: "Only visible to jobs that reference that specific environment", code: "jobs:\n  deploy-staging:\n    environment: staging   # sees staging secrets only" },
        { term: "OIDC federation (secretless deploy)", desc: "Exchange a short-lived GitHub token for temporary cloud credentials — no static keys", code: "permissions:\n  id-token: write\nsteps:\n  - uses: aws-actions/configure-aws-credentials@v4\n    with:\n      role-to-assume: arn:aws:iam::123:role/deploy\n      aws-region: us-east-1" },
      ],
    },
    {
      title: "Debugging & Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "Debug logging", desc: "Verbose per-step + runner diagnostics", code: "# set as repo secrets:\nACTIONS_STEP_DEBUG=true\nACTIONS_RUNNER_DEBUG=true" },
        { term: "Print a whole context", desc: "Inspect an expression that isn't resolving as expected", code: "- run: echo '\\${{ toJSON(github) }}'" },
        { term: "actionlint", desc: "Static-analyze workflow YAML before it ever runs", code: "actionlint .github/workflows/*.yml" },
        { term: "act", desc: "Run workflows locally in Docker for fast iteration", code: "act push\nact pull_request\nact -j test" },
        { term: "Failure notification", desc: "Route deploy/scheduled-workflow failures to a channel", code: "- if: failure()\n  uses: slackapi/slack-github-action@v2\n  with:\n    payload: '{\"text\":\"deploy failed\"}'" },
        { term: "Required status checks", desc: "Branch protection reads job check-runs to gate merges", code: "# Settings > Branches > Require status checks to pass\n# select: lint, unit-tests, integration-tests" },
        { term: "Health of a pipeline", desc: "What senior teams actually watch", code: "# failure rate per workflow\n# p95 job duration\n# minutes consumed per repo/team\n# time-to-green on PRs" },
        { term: "GITHUB_OUTPUT / GITHUB_ENV", desc: "Special files a step writes to for output passing", code: "echo \"key=value\" >> \"$GITHUB_OUTPUT\"\necho \"VAR=value\" >> \"$GITHUB_ENV\"" },
        { term: "GitHub-hosted vs self-hosted", desc: "Managed + ephemeral, no private network vs your machine, full control", code: "runs-on: ubuntu-latest   # GitHub-hosted\nruns-on: [self-hosted, linux, gpu]   # your runner, custom labels" },
      ],
    },
  ],
};

export default githubActions;
