import type { CheatSheetData } from "./types";

/**
 * Cheat sheet registry — mirrors the skill content registry.
 * Lazy-loaded so cheat sheet data never bloats pages that don't use it.
 */
const REGISTRY: Record<string, () => Promise<{ default: CheatSheetData }>> = {
  python: () => import("./python"),
  javascript: () => import("./javascript"),
  typescript: () => import("./typescript"),
  go: () => import("./go"),
  rust: () => import("./rust"),
  java: () => import("./java"),
  fastapi: () => import("./fastapi"),
  cpp: () => import("./cpp"),
  django: () => import("./django"),
  flask: () => import("./flask"),
  express: () => import("./express"),
  "spring-boot": () => import("./spring-boot"),
  nodejs: () => import("./nodejs"),
  nestjs: () => import("./nestjs"),
  postgresql: () => import("./postgresql"),
  mysql: () => import("./mysql"),
  mongodb: () => import("./mongodb"),
  redis: () => import("./redis"),
  neo4j: () => import("./neo4j"),
  elasticsearch: () => import("./elasticsearch"),
  clickhouse: () => import("./clickhouse"),
  sqlite: () => import("./sqlite"),
  faiss: () => import("./faiss"),
  pinecone: () => import("./pinecone"),
  milvus: () => import("./milvus"),
  weaviate: () => import("./weaviate"),
  qdrant: () => import("./qdrant"),
  chroma: () => import("./chroma"),
  oauth: () => import("./oauth"),
  jwt: () => import("./jwt"),
  "cookies-sessions": () => import("./cookies-sessions"),
  rbac: () => import("./rbac"),
  abac: () => import("./abac"),
  rest: () => import("./rest"),
  graphql: () => import("./graphql"),
  grpc: () => import("./grpc"),
  websockets: () => import("./websockets"),
  sse: () => import("./sse"),
  linux: () => import("./linux"),
  networking: () => import("./networking"),
  "operating-systems": () => import("./operating-systems"),
  dsa: () => import("./dsa"),
  algorithms: () => import("./algorithms"),
  oop: () => import("./oop"),
  solid: () => import("./solid"),
  "design-patterns": () => import("./design-patterns"),
  concurrency: () => import("./concurrency"),
  multithreading: () => import("./multithreading"),
  "caching-cs": () => import("./caching-cs"),
  "sql-injection": () => import("./sql-injection"),
  xss: () => import("./xss"),
  csrf: () => import("./csrf"),
  encryption: () => import("./encryption"),
  hashing: () => import("./hashing"),
  "tls-https": () => import("./tls-https"),
  "secrets-management": () => import("./secrets-management"),
  "owasp-top-10": () => import("./owasp-top-10"),
  aws: () => import("./aws"),
  azure: () => import("./azure"),
  gcp: () => import("./gcp"),
  docker: () => import("./docker"),
  kubernetes: () => import("./kubernetes"),
  terraform: () => import("./terraform"),
  cicd: () => import("./cicd"),
  "github-actions": () => import("./github-actions"),
  jenkins: () => import("./jenkins"),
  git: () => import("./git"),
  logging: () => import("./logging"),
  metrics: () => import("./metrics"),
  tracing: () => import("./tracing"),
  prometheus: () => import("./prometheus"),
  grafana: () => import("./grafana"),
  opentelemetry: () => import("./opentelemetry"),
  "distributed-systems": () => import("./distributed-systems"),
  "cap-theorem": () => import("./cap-theorem"),
  "load-balancers": () => import("./load-balancers"),
  "reverse-proxy": () => import("./reverse-proxy"),
  "api-gateway": () => import("./api-gateway"),
  cdn: () => import("./cdn"),
  "caching-systems": () => import("./caching-systems"),
  "message-queues": () => import("./message-queues"),
  kafka: () => import("./kafka"),
  rabbitmq: () => import("./rabbitmq"),
  "machine-learning": () => import("./machine-learning"),
  "deep-learning": () => import("./deep-learning"),
  "neural-networks": () => import("./neural-networks"),
  cnn: () => import("./cnn"),
  rnn: () => import("./rnn"),
  transformers: () => import("./transformers"),
  attention: () => import("./attention"),
  embeddings: () => import("./embeddings"),
  "vector-search": () => import("./vector-search"),
};

export const hasCheatSheet = (slug: string): boolean => slug in REGISTRY;

export async function loadCheatSheet(slug: string): Promise<CheatSheetData | null> {
  const loader = REGISTRY[slug];
  if (!loader) return null;
  return (await loader()).default;
}
