import type { CheatSheetData } from "./types";

const jenkins: CheatSheetData = {
  title: "The Ultimate Jenkins Cheat Sheet",
  subtitle: "Pipeline syntax · controller/agent architecture · credentials · production toolbelt",
  sections: [
    {
      title: "Core Pipeline Syntax",
      color: "violet",
      rows: [
        { term: "pipeline { }", desc: "Top-level Declarative Pipeline block", code: "pipeline {\n    agent any\n    stages { }\n}" },
        { term: "agent", desc: "Where the pipeline (or a stage) runs", code: "agent any\nagent none\nagent { label 'linux && docker' }" },
        { term: "stages / stage", desc: "Ordered phases shown as UI columns", code: "stages {\n    stage('Build') { steps { } }\n}" },
        { term: "steps", desc: "Individual commands inside a stage", code: "steps {\n    sh 'make build'\n    echo 'done'\n}" },
        { term: "sh / bat", desc: "Run a shell (Linux) or batch (Windows) command", code: "sh 'make test'\nbat 'msbuild app.sln'" },
        { term: "checkout scm", desc: "Pull source using the job's configured SCM", code: "stage('Checkout') {\n    steps { checkout scm }\n}" },
        { term: "post { }", desc: "Actions after stage/pipeline completion", code: "post {\n    success { echo 'ok' }\n    failure { echo 'notify' }\n    always { junit 'reports/*.xml' }\n}" },
        { term: "when { }", desc: "Conditionally run a stage", code: "when { branch 'main' }\nwhen { expression { params.ENV == 'prod' } }" },
        { term: "environment { }", desc: "Define env vars for the pipeline/stage", code: "environment {\n    APP_NAME = 'orders-service'\n}" },
        { term: "parameters { }", desc: "Adds a UI input form to the job", code: "parameters {\n    choice(name: 'ENV', choices: ['staging','prod'])\n    string(name: 'TAG', defaultValue: 'latest')\n}" },
        { term: "options { }", desc: "Pipeline-level behavior settings", code: "options {\n    timeout(time: 30, unit: 'MINUTES')\n    timestamps()\n    disableConcurrentBuilds()\n}" },
        { term: "triggers { }", desc: "How a build starts automatically", code: "triggers {\n    pollSCM('H/5 * * * *')  // legacy; prefer webhooks\n    cron('H 2 * * *')\n}" },
        { term: "script { }", desc: "Drop into raw Groovy inside Declarative", code: "steps {\n    script {\n        if (env.BRANCH_NAME == 'main') { sh 'deploy.sh' }\n    }\n}" },
        { term: "node('label') { }", desc: "Scripted Pipeline top-level block", code: "node('linux') {\n    stage('Build') { sh 'make build' }\n}" },
        { term: "retry(n) { }", desc: "Re-run a step block on failure", code: "retry(3) {\n    sh './flaky-integration-tests.sh'\n}" },
      ],
    },
    {
      title: "Architecture: Controller, Agents & Labels",
      color: "blue",
      rows: [
        { term: "Controller (master)", desc: "Schedules builds, hosts UI, stores config/credentials", code: "// production rule: never run build STEPS on the controller\n// disable executors on the built-in node" },
        { term: "Agent (slave/worker/node)", desc: "Machine or pod that executes build steps", code: "agent { label 'linux && docker' }" },
        { term: "Label expression", desc: "Route work to matching agents", code: "label 'gpu && cuda12'\nlabel 'windows || linux'" },
        { term: "Static agent", desc: "Long-lived VM registered with the controller", code: "// Manage Jenkins > Nodes > New Node\n// connects via inbound TCP (port 50000) or SSH" },
        { term: "Dynamic K8s agent", desc: "Ephemeral pod provisioned per build, then torn down", code: "agent {\n    kubernetes {\n        yaml '''\napiVersion: v1\nkind: Pod\nspec:\n  containers:\n  - name: builder\n    image: maven:3.9\n'''\n    }\n}" },
        { term: "container('name') { }", desc: "Run steps inside a specific pod container", code: "container('builder') {\n    sh 'mvn -B verify'\n}" },
        { term: "Jenkinsfile", desc: "Pipeline-as-code file checked into the repo", code: "// checked in at repo root as 'Jenkinsfile'\n// read fresh from source control on every build" },
        { term: "JCasC (Configuration as Code)", desc: "Controller's own config defined as version-controlled YAML", code: "CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml" },
        { term: "Blue Ocean", desc: "Jenkins' modernized visual pipeline UI", code: "// stage-by-stage flow view vs classic UI's console list" },
        { term: "matrix { }", desc: "Expand into one parallel stage per axis combination", code: "matrix {\n    axes {\n        axis { name 'PY'; values '3.11','3.12' }\n    }\n    stages { stage('Test'){ steps { sh 'run.sh' } } }\n}" },
      ],
    },
    {
      title: "Credentials & Secrets",
      color: "emerald",
      rows: [
        { term: "withCredentials", desc: "Inject a secret scoped to one step block only", code: "withCredentials([usernamePassword(\n    credentialsId: 'reg-creds',\n    usernameVariable: 'U', passwordVariable: 'P')]) {\n    sh 'echo P | docker login -u U --password-stdin'\n}" },
        { term: "string() binding", desc: "Bind a single secret text value", code: "withCredentials([string(\n    credentialsId: 'api-token', variable: 'TOKEN')]) {\n    sh 'curl -H \"Authorization: TOKEN\" api.example.com'\n}" },
        { term: "file() binding", desc: "Bind a secret file (e.g. kubeconfig)", code: "withCredentials([file(\n    credentialsId: 'k8s-kubeconfig', variable: 'KUBECONFIG')]) {\n    sh 'kubectl apply -f deploy.yaml'\n}" },
        { term: "credentials() in environment", desc: "Shortcut binding inside environment block", code: "environment {\n    DB_PASSWORD = credentials('db-password')\n}" },
        { term: "Credential scope", desc: "Global vs folder vs job-level visibility", code: "// prefer folder/job scoped credentials\n// avoid defining everything as a global credential" },
        { term: "Never do this", desc: "The classic leak pattern", code: "sh 'env'                 // dumps secrets to console\necho \"password=PASS\"     // never echo a credential var" },
        { term: "Jenkins masking", desc: "Console log auto-masks known credential values", code: "// masking is a safety net, not a substitute\n// for scoping secrets narrowly" },
        { term: "Secrets Manager pairing", desc: "For rotation/leasing/audit beyond Jenkins' own store", code: "// see the Secrets Management skill for vault-based\n// short-lived tokens and rotation policies" },
      ],
    },
    {
      title: "Shared Libraries & Reuse",
      color: "amber",
      rows: [
        { term: "@Library annotation", desc: "Import a versioned Shared Library into a Jenkinsfile", code: "@Library('company-lib@v2.3.0') _\nstandardBuild(agentLabel: 'linux', buildCmd: 'make build')" },
        { term: "vars/ directory", desc: "Global pipeline steps callable by name", code: "// vars/standardBuild.groovy\ndef call(Map config) {\n    sh config.buildCmd\n}" },
        { term: "src/ directory", desc: "Ordinary Groovy classes used by vars/ steps", code: "// src/org/company/Deployer.groovy\nclass Deployer { def deploy(String tag) { ... } }" },
        { term: "resources/ directory", desc: "Static templates (manifests, config) loaded by libraryResource", code: "def yaml = libResource('org/company/deploy-template.yaml')" },
        { term: "Version pinning", desc: "Consumers upgrade deliberately, not automatically", code: "@Library('company-lib@v3.0.0') _   // bump deliberately per consumer" },
        { term: "JenkinsPipelineUnit", desc: "Unit-test Shared Library Groovy without a real controller", code: "def script = loadScript('vars/standardBuild.groovy')\nscript.call([buildCmd: 'make build'])\nassertJobStatusSuccess()" },
        { term: "When to extract a library", desc: "Rule of thumb for reuse", code: "// once the same stage block is copy-pasted into\n// 3+ Jenkinsfiles, extract it into a Shared Library" },
      ],
    },
    {
      title: "Pitfalls & Gotchas",
      color: "rose",
      rows: [
        { term: "Building on the controller", desc: "Wastes scheduler capacity, expands blast radius", code: "// WRONG: agent any + executors enabled on built-in node\n// RIGHT: agent { label 'linux' } + 0 executors on controller" },
        { term: "No timeout set", desc: "A hung step occupies an executor forever", code: "options { timeout(time: 30, unit: 'MINUTES') }" },
        { term: "Plugin auto-update in prod", desc: "Most common cause of a broken controller", code: "// pin exact versions in plugins.txt\n// test upgrades on a staging controller first" },
        { term: "Script Console misuse", desc: "Admin-only feature = unrestricted RCE by design", code: "// Manage Jenkins > Script Console\n// restrict access tightly via role-based authorization" },
        { term: "SCM polling over webhooks", desc: "Wastes cycles, adds minutes of trigger latency", code: "// prefer a webhook from the Git host\n// pollSCM only when webhooks aren't reachable (air-gapped)" },
        { term: "Copy-pasted Jenkinsfiles", desc: "A fix has to be manually reapplied everywhere", code: "// extract to a Shared Library instead of duplicating stages" },
        { term: "Global credentials everywhere", desc: "One compromised job can read every secret", code: "// scope credentials to the folder/job that needs them" },
        { term: "Scripted by default", desc: "Unrestricted Groovy only the author can maintain", code: "// default to Declarative; use script{} only when needed" },
        { term: "Unbounded build history", desc: "Slows controller disk and UI over time", code: "// configure discard-old-builds policy per job" },
        { term: "No jenkins_home backup", desc: "Loses entire job history, config, and credentials store", code: "// back up jenkins_home on a schedule; test the restore" },
      ],
    },
    {
      title: "Production Toolbelt & Ops",
      color: "cyan",
      rows: [
        { term: "Run Jenkins (Docker)", desc: "Quickest local/prod controller start", code: "docker run -d -p 8080:8080 -p 50000:50000 \\\n  -v jenkins_home:/var/jenkins_home \\\n  jenkins/jenkins:lts" },
        { term: "Initial admin password", desc: "First-login secret", code: "docker exec jenkins cat \\\n  /var/jenkins_home/secrets/initialAdminPassword" },
        { term: "Pipeline syntax validator", desc: "Interactive Declarative syntax generator/linter", code: "// visit /pipeline-syntax/ on your controller" },
        { term: "Replay", desc: "Edit and re-run a build's Jenkinsfile without committing", code: "// build page > Replay" },
        { term: "Thread dump / support bundle", desc: "Diagnose a frozen or slow controller", code: "// Manage Jenkins > System Information\n// or Support Core plugin > Generate Support Bundle" },
        { term: "Prometheus metrics", desc: "Controller health for alerting", code: "// /prometheus endpoint exposes:\n// jenkins_queue_size_value\n// jenkins_executor_in_use_value\n// jvm_memory_used_bytes" },
        { term: "junit step", desc: "Publish structured test results", code: "post {\n    always { junit '**/build/test-results/**/*.xml' }\n}" },
        { term: "slackSend / emailext", desc: "Post-build notifications", code: "post {\n    failure {\n        slackSend(channel: '#builds', color: 'danger',\n                  message: 'Build failed - check console')\n    }\n}" },
        { term: "Deploy stage pattern", desc: "Typical final pipeline stage", code: "stage('Deploy') {\n    when { branch 'main' }\n    steps { sh 'kubectl set image deployment/app app=app:tag' }\n}" },
        { term: "Restart from Stage", desc: "Re-run only the failed stage onward", code: "// build page > Restart from Stage (classic or Blue Ocean UI)" },
        { term: "Security advisories", desc: "Check before any core/plugin upgrade", code: "// jenkins.io/security/advisories/" },
      ],
    },
  ],
};

export default jenkins;
