import type { CheatSheetData } from "./types";

const python: CheatSheetData = {
  title: "The Ultimate Python Cheat Sheet",
  subtitle: "Core language · data structures · idioms · production toolbelt",
  sections: [
    {
      title: "Keywords",
      color: "violet",
      rows: [
        { term: "False / True", desc: "Boolean data type", code: "1 > 2 is False\n'a' in 'abc' is True" },
        { term: "and / or / not", desc: "Logical operators", code: "x and y  # both\nx or y   # at least one\nnot x    # negation" },
        { term: "if / elif / else", desc: "Conditional execution", code: "if x > 3: big()\nelif x == 3: mid()\nelse: small()" },
        { term: "for / while", desc: "Loops", code: "for x in [1, 2, 3]: print(x)\nwhile x < 10: x += 1" },
        { term: "break / continue", desc: "Exit loop / skip to next iteration", code: "for x in xs:\n    if bad(x): continue\n    if done(x): break" },
        { term: "def / return", desc: "Define a function and its result", code: "def add(a, b=2):\n    return a + b" },
        { term: "lambda", desc: "Anonymous inline function", code: "square = lambda x: x * x" },
        { term: "class", desc: "Define a class", code: "class Dog:\n    def bark(self): ..." },
        { term: "in / is", desc: "Membership test / identity test", code: "3 in [1, 2, 3]   # True\nx is None        # identity" },
        { term: "None", desc: "The null value — absence of data", code: "result = None" },
        { term: "try / except / finally", desc: "Handle exceptions", code: "try: risky()\nexcept ValueError as e: fix(e)\nfinally: cleanup()" },
        { term: "with", desc: "Context manager — auto setup/teardown", code: "with open('f.txt') as f:\n    data = f.read()" },
        { term: "import / from / as", desc: "Use code from other modules", code: "import math\nfrom pathlib import Path as P" },
        { term: "yield", desc: "Produce values lazily (generator)", code: "def naturals():\n    n = 0\n    while True:\n        yield n; n += 1" },
        { term: "async / await", desc: "Cooperative concurrency", code: "async def main():\n    await fetch(url)" },
        { term: "match / case", desc: "Structural pattern matching (3.10+)", code: "match cmd:\n    case ['go', d]: move(d)\n    case _: help()" },
        { term: "global / nonlocal", desc: "Rebind names in outer scopes", code: "def inc():\n    global counter\n    counter += 1" },
        { term: "assert / raise / pass / del", desc: "Sanity checks, throw errors, no-op, delete names", code: "assert x > 0, 'must be +'\nraise ValueError('bad')\ndel cache[key]" },
      ],
    },
    {
      title: "Basic Data Structures",
      color: "blue",
      rows: [
        { term: "int / float", desc: "Whole and decimal numbers — int is arbitrary precision", code: "n = 2 ** 100      # fine!\nx = 3.14\n7 // 2, 7 % 2, divmod(7, 2)" },
        { term: "bool", desc: "Truthiness: empty things are falsy", code: "bool(0), bool(''), bool([])  # all False\nbool(-1), bool('a')          # True" },
        { term: "str", desc: "Immutable text; rich methods", code: "s = 'hello world'\ns.upper()  s.title()  s.strip()\ns.split(' ')  '-'.join(parts)\ns.replace('l', 'L')  s.startswith('he')\ns[0]  s[-1]  s[2:5]  s[::-1]" },
        { term: "f-string", desc: "Fast, readable interpolation + formatting", code: "f'{name} is {age}'\nf'{pi:.2f}'    # 3.14\nf'{n:,}'       # 1,000,000\nf'{x=}'        # debug: x=5" },
        { term: "list", desc: "Ordered, mutable sequence", code: "xs = [1, 2, 3]\nxs.append(4)  xs.insert(0, 9)\nxs.pop()  xs.remove(2)\nxs.sort()  xs.reverse()\nxs[0]  xs[-1]  xs[1:3]  len(xs)" },
        { term: "tuple", desc: "Ordered, immutable — hashable, unpackable", code: "pt = (3, 4)\nx, y = pt\na, *rest = [1, 2, 3, 4]" },
        { term: "dict", desc: "Key → value hash map, insertion-ordered", code: "d = {'a': 1, 'b': 2}\nd['c'] = 3\nd.get('z', 0)   # default\nd.keys()  d.values()  d.items()\nfor k, v in d.items(): ...\nd.setdefault('e', []).append(1)\n{**d1, **d2}    # merge  (or d1 | d2)" },
        { term: "set", desc: "Unique elements; O(1) membership; set algebra", code: "s = {1, 2, 3}\ns.add(4)  s.discard(1)\na | b   # union\na & b   # intersection\na - b   # difference\nx in s  # O(1)" },
        { term: "Slicing", desc: "seq[start:stop:step] — works on str/list/tuple", code: "xs[2:]  xs[:3]  xs[::2]\nxs[::-1]        # reversed copy\nxs[:]           # shallow copy" },
      ],
    },
    {
      title: "Comprehensions & Iteration",
      color: "emerald",
      rows: [
        { term: "List comp", desc: "Transform + filter in one expression", code: "[x * x for x in range(10) if x % 2 == 0]" },
        { term: "Dict / set comp", desc: "Same idea, braces", code: "{u.id: u for u in users}\n{w.lower() for w in words}" },
        { term: "Generator expr", desc: "Lazy — constant memory, one pass", code: "total = sum(len(l) for l in lines)" },
        { term: "enumerate", desc: "Index + value while looping", code: "for i, x in enumerate(xs, start=1): ..." },
        { term: "zip", desc: "Iterate sequences in parallel", code: "for name, score in zip(names, scores): ..." },
        { term: "sorted", desc: "Sort anything with a key function", code: "sorted(users, key=lambda u: u.age, reverse=True)" },
        { term: "any / all", desc: "Boolean reduction over iterables", code: "any(x < 0 for x in xs)\nall(u.active for u in users)" },
        { term: "itertools gold", desc: "Iterator building blocks", code: "from itertools import chain, islice, groupby, product\nchain(a, b)      islice(gen, 10)\nproduct([1,2], 'ab')" },
        { term: "collections gold", desc: "Specialized containers", code: "from collections import Counter, defaultdict, deque\nCounter(words).most_common(3)\ndefaultdict(list)[k].append(v)\ndeque(maxlen=100)  # ring buffer" },
      ],
    },
    {
      title: "Functions & Classes",
      color: "amber",
      rows: [
        { term: "*args / **kwargs", desc: "Capture extra positional / keyword args", code: "def f(*args, **kwargs):\n    g(*args, **kwargs)  # forward" },
        { term: "Keyword-only args", desc: "Force clarity at the call site", code: "def move(dist, *, unit='m'): ...\nmove(5, unit='km')" },
        { term: "Decorator", desc: "Wrap a function to add behavior", code: "@functools.wraps(func)\ndef wrapper(*a, **kw):\n    return func(*a, **kw)" },
        { term: "dataclass", desc: "Auto __init__/__repr__/__eq__", code: "@dataclass(frozen=True, slots=True)\nclass User:\n    id: int\n    name: str = 'anon'" },
        { term: "property", desc: "Computed attribute with method logic", code: "@property\ndef area(self):\n    return self.w * self.h" },
        { term: "classmethod / staticmethod", desc: "Alternative constructors / namespaced helpers", code: "@classmethod\ndef from_json(cls, s): ...\n@staticmethod\ndef validate(x): ..." },
        { term: "Dunder methods", desc: "Make objects feel built-in", code: "__init__ __repr__ __eq__ __hash__\n__len__ __iter__ __getitem__\n__enter__ __exit__ __call__" },
        { term: "Inheritance + super()", desc: "Cooperative — follows the MRO", code: "class Cat(Animal):\n    def __init__(self, name):\n        super().__init__(name)" },
        { term: "Type hints", desc: "Static safety; powers FastAPI/Pydantic", code: "def get(id: int) -> User | None: ...\nxs: list[str]  d: dict[str, int]\nfrom typing import Protocol" },
      ],
    },
    {
      title: "Errors, Files & Modules",
      color: "rose",
      rows: [
        { term: "Exception idiom", desc: "Catch narrowly, chain causes", code: "try: parse(raw)\nexcept (ValueError, KeyError) as e:\n    raise AppError('bad input') from e" },
        { term: "Custom exceptions", desc: "Domain-specific error hierarchy", code: "class PaymentError(Exception): ...\nclass NoFunds(PaymentError): ..." },
        { term: "pathlib", desc: "Modern file paths — use instead of os.path", code: "from pathlib import Path\np = Path('data') / 'file.txt'\np.read_text()  p.exists()\np.glob('*.csv')" },
        { term: "File I/O", desc: "Always with a context manager", code: "with open('f.txt', encoding='utf-8') as f:\n    for line in f: ...\nwith open('out.txt', 'w') as f:\n    f.write(text)" },
        { term: "JSON", desc: "Serialize / parse", code: "import json\ns = json.dumps(obj, indent=2)\nobj = json.loads(s)" },
        { term: "Module & main guard", desc: "Import = run once; guard the entry point", code: "if __name__ == '__main__':\n    main()" },
        { term: "Virtual env (uv)", desc: "The modern toolchain", code: "uv init proj && cd proj\nuv add fastapi\nuv run python main.py\nuv run pytest" },
      ],
    },
    {
      title: "Async & Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "asyncio basics", desc: "One thread, many concurrent tasks", code: "async def main():\n    r = await client.get(url)\nasyncio.run(main())" },
        { term: "Run concurrently", desc: "gather / TaskGroup (3.11+)", code: "results = await asyncio.gather(*coros)\nasync with asyncio.TaskGroup() as tg:\n    tg.create_task(job())" },
        { term: "Never block the loop", desc: "The #1 async bug", code: "await asyncio.sleep(1)   # YES\ntime.sleep(1)            # NO — freezes all" },
        { term: "GIL rule of thumb", desc: "Pick the right concurrency tool", code: "IO-bound many  -> asyncio\nIO-bound few   -> threads\nCPU-bound      -> multiprocessing" },
        { term: "functools.cache", desc: "Memoize pure functions", code: "@functools.lru_cache(maxsize=256)\ndef fib(n): ..." },
        { term: "Logging", desc: "Never print in production", code: "log = logging.getLogger(__name__)\nlog.info('order=%s ok', oid)" },
        { term: "Testing (pytest)", desc: "Plain asserts + fixtures", code: "def test_add():\n    assert add(2, 2) == 4\nwith pytest.raises(ValueError): ..." },
        { term: "Debug fast", desc: "Built-in breakpoint", code: "breakpoint()   # drops into pdb\npython -m cProfile app.py" },
        { term: "Money & time traps", desc: "Two classics", code: "Decimal('0.1') + Decimal('0.2')\ndatetime.now(tz=timezone.utc)" },
        { term: "Secrets", desc: "Cryptographically safe tokens", code: "secrets.token_urlsafe(32)" },
      ],
    },
  ],
};

export default python;
