import type { CheatSheetData } from "./types";

const rbac: CheatSheetData = {
  title: "The Ultimate RBAC Cheat Sheet",
  subtitle: "NIST model · hierarchies & constraints · FastAPI pattern · Kubernetes · multi-tenant · pitfalls",
  sections: [
    {
      title: "Core Model & Terms",
      color: "violet",
      rows: [
        { term: "User", desc: "An already-authenticated identity; RBAC never establishes WHO you are", code: "user.id -> resolved by JWT/OAuth/session\nRBAC starts AFTER identity is known" },
        { term: "Role", desc: "A named bundle of permissions mapped to a job function", code: "role: 'editor'\nrole: 'invoice-approver'" },
        { term: "Permission", desc: "Approval to do one operation on one resource type", code: "'invoices:approve'\n'documents:write'\nconvention: resource:action" },
        { term: "Session", desc: "Runtime instant where a user activates some subset of assigned roles", code: "activated_roles = {'editor'}  # this request only" },
        { term: "RBAC0", desc: "Flat model — users, roles, permissions, no hierarchy, no constraints", code: "base case: every real system extends this" },
        { term: "RBAC1", desc: "Adds role hierarchy — senior role inherits junior role's permissions", code: "admin extends editor extends viewer" },
        { term: "RBAC2", desc: "Adds constraints (SoD, cardinality) on a flat model, no hierarchy", code: "cannot hold both invoice-creator + invoice-approver" },
        { term: "RBAC3", desc: "Hierarchy AND constraints combined — the full NIST model", code: "most mature production systems land here" },
        { term: "Authentication vs authorization", desc: "WHO you are vs WHAT you can do", code: "authn -> OAuth/JWT/Cookies skills\nauthz -> RBAC (this page)" },
        { term: "401 vs 403", desc: "Identity unresolved vs identity known, permission denied", code: "401 Unauthorized -> authn failed\n403 Forbidden    -> authz failed" },
        { term: "Default-deny", desc: "Absence of an explicit grant must mean no access, always", code: "if permission not in effective_set: deny\nNEVER allow-unless-blocked" },
        { term: "Least privilege", desc: "Start every new role/user at zero permissions, add explicitly", code: "new_role = Role(permissions=set())\n# add only what's justified" },
        { term: "Resource:action naming", desc: "Flat, greppable permission namespace", code: "'users:manage'  'pods:list'  'orders:refund'" },
      ],
    },
    {
      title: "Data Model & Resolution",
      color: "blue",
      rows: [
        { term: "users table", desc: "The authenticated identity, nothing about access here", code: "users(id, email, ...)" },
        { term: "roles table", desc: "Named role plus optional parent for RBAC1 hierarchy", code: "roles(id, name, parent_id)" },
        { term: "permissions table", desc: "The flat catalog of resource:action strings", code: "permissions(id, name)" },
        { term: "user_roles join table", desc: "Many-to-many assignment of users to roles", code: "user_roles(user_id, role_id)" },
        { term: "role_permissions join table", desc: "Many-to-many grant of permissions to roles", code: "role_permissions(role_id, permission_id)" },
        { term: "Multi-tenant scoping", desc: "Scope the ASSIGNMENT to an org, not the role definition", code: "user_org_roles(user_id, org_id, role_id)" },
        { term: "Hierarchy resolution (cycle-safe)", desc: "Union a role's own perms with its parent's, guarding against cycles", code: "def resolve(role, seen=None):\n  seen = seen or set()\n  if role.id in seen: return set()\n  seen.add(role.id)\n  p = set(role.permissions)\n  if role.parent: p |= resolve(role.parent, seen)\n  return p" },
        { term: "Effective permissions", desc: "Union across ALL of a user's assigned roles", code: "def effective(user):\n  out = set()\n  for r in user.roles:\n    out |= resolve(r)\n  return out" },
        { term: "Diamond inheritance", desc: "Same ancestor reachable via two paths — memoize per role id", code: "cache = {}\ncache.setdefault(role.id, resolve(role))" },
        { term: "Index the join tables", desc: "Unindexed user_roles/role_permissions is the #1 slow-check cause", code: "CREATE INDEX ON user_roles(user_id)\nCREATE INDEX ON role_permissions(role_id)" },
      ],
    },
    {
      title: "FastAPI Pattern & Everyday Checks",
      color: "emerald",
      rows: [
        { term: "get_current_user", desc: "Existing authentication dependency — resolves the identity", code: "def get_current_user(creds=Depends(bearer)):\n  return decode_and_load_user(creds)" },
        { term: "require_permission factory", desc: "Generalizes a single require_admin flag into named permissions", code: "def require_permission(perm):\n  def check(user=Depends(get_current_user)):\n    if perm not in effective(user):\n      raise HTTPException(403, 'Missing: ' + perm)\n    return user\n  return check" },
        { term: "Protecting a route", desc: "Apply the dependency at the route, not inside the handler body", code: "@router.post('/invoices/{id}/approve')\ndef approve(id: int,\n  user=Depends(require_permission('invoices:approve'))):\n  ..." },
        { term: "Multi-tenant check", desc: "Always pass org/tenant id explicitly into the resolver", code: "def require_permission(perm):\n  def check(user=Depends(get_current_user), org_id=Depends(get_org)):\n    if perm not in effective_in_org(user, org_id):\n      raise HTTPException(403, 'Missing: ' + perm)\n  return check" },
        { term: "Role name check (avoid)", desc: "Anti-pattern — couples logic to a specific role name", code: "if user.role == 'editor': ...   # WRONG\nif 'documents:write' in effective(user): ...  # RIGHT" },
        { term: "Superadmin bypass (avoid)", desc: "Defeats every constraint including separation of duties", code: "if user.is_superadmin or perm in effective(user): # WRONG\nif perm in effective(user): # RIGHT, no bypass" },
        { term: "Assigning a role", desc: "Reject the assignment if it creates an SoD conflict first", code: "def assign_role(user, role, conflicts):\n  check_sod_violation(user.roles, role, conflicts)\n  user.roles.add(role)" },
        { term: "Debug helper", desc: "Explain exactly why a user does/doesn't have access", code: "def explain(user, perm):\n  r = effective(user)\n  return {'roles': [x.name for x in user.roles],\n          'resolved': sorted(r), 'has': perm in r}" },
      ],
    },
    {
      title: "Constraints & Multi-Tenant",
      color: "amber",
      rows: [
        { term: "Static SoD (SSD)", desc: "Cannot HOLD two conflicting roles simultaneously — checked at assignment", code: "conflicts = {frozenset({'invoice-creator','invoice-approver'})}\nblock assignment if proposed set contains a full pair" },
        { term: "Dynamic SoD (DSD)", desc: "Can hold both roles, cannot ACTIVATE both in one session", code: "checked at session-activation time, not assignment time" },
        { term: "Cardinality constraint", desc: "Limits like max members per role, or one active session at a time", code: "max_active_sessions('break-glass-admin') == 1" },
        { term: "SoD conflict checker", desc: "Refuse a proposed role change that creates a banned pair", code: "def check_sod(current, new_role, conflicts):\n  proposed = current | {new_role}\n  for pair in conflicts:\n    if pair.issubset(proposed):\n      return (pair - {new_role}).pop()\n  return None" },
        { term: "Org-scoped assignment", desc: "Same user, different role per organization", code: "user_org_roles(user_id, org_id, role_id)\nalice: admin in org A, viewer in org B" },
        { term: "Cross-tenant leak (avoid)", desc: "Missing org_id in the permission check is the classic multi-tenant bug", code: "effective_in_org(user, org_id)  # ALWAYS pass org_id\nnever: effective(user)  # global, unscoped" },
        { term: "Role explosion", desc: "Combinatorial near-duplicate roles from encoding region/dept/time as roles", code: "BAD:  Editor-RegionA, Editor-RegionB, ...\nGOOD: Editor + region attribute checked at ABAC layer" },
        { term: "Role explosion fix", desc: "Parameterize, or push the dimension to ABAC", code: "see ABAC skill: 'next step up in flexibility'" },
        { term: "Static vs dynamic assignment", desc: "Standing role vs time-bound just-in-time elevation", code: "static: assigned indefinitely\ndynamic: JIT/break-glass, expires automatically" },
      ],
    },
    {
      title: "Kubernetes RBAC",
      color: "rose",
      rows: [
        { term: "Role", desc: "Namespace-scoped permission rules — verbs on API resources", code: "kind: Role\nmetadata: {namespace: payments, name: pod-reader}\nrules: [{apiGroups: [''], resources: ['pods'], verbs: ['get','list','watch']}]" },
        { term: "ClusterRole", desc: "Cluster-wide rules, or rules for cluster-scoped resources (e.g. Nodes)", code: "kind: ClusterRole\nmetadata: {name: node-reader}" },
        { term: "RoleBinding", desc: "Assigns a Role to a Subject within one namespace — the User-Role assignment step", code: "kind: RoleBinding\nsubjects: [{kind: User, name: jane}]\nroleRef: {kind: Role, name: pod-reader}" },
        { term: "ClusterRoleBinding", desc: "Assigns a ClusterRole cluster-wide", code: "kind: ClusterRoleBinding\nsubjects: [{kind: Group, name: platform-admins}]" },
        { term: "Subject kinds", desc: "Who a binding can attach a role to", code: "User | Group | ServiceAccount" },
        { term: "ServiceAccount", desc: "The non-human identity in-cluster workloads use — bind roles the same way", code: "kind: ServiceAccount\nname: payments-worker" },
        { term: "Check effective access", desc: "Ask the API server directly whether an action would be allowed", code: "kubectl auth can-i list pods --namespace=payments\nkubectl auth can-i delete pods --as=jane" },
        { term: "No native hierarchy/SoD", desc: "Kubernetes RBAC has neither — layer OPA Gatekeeper/Kyverno for that richness", code: "policy engines sit ON TOP of native RBAC" },
      ],
    },
    {
      title: "Pitfalls, Security & Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "Authn != authz (avoid)", desc: "A valid token proves identity only — always check permission separately", code: "WRONG: if authenticated: allow()\nRIGHT: if perm in effective(user): allow()" },
        { term: "Client-only enforcement (avoid)", desc: "Hiding a UI button is not a security boundary", code: "server MUST re-check every protected endpoint\nregardless of what the UI would allow clicking" },
        { term: "Stale cache (avoid)", desc: "Revoked role still works until cache/TTL expires — pair caching with invalidation", code: "on role/permission mutation -> publish invalidation event\nnever rely on TTL alone for revocation" },
        { term: "Cache key pattern", desc: "Version-tag the cached effective set for correct busting", code: "redis key: perms:{user_id}:{org_id}:v{version}\nbump version on ANY role/permission edit" },
        { term: "Tampered role claims", desc: "Never trust a JWT role claim without verifying the signature first", code: "verify signature -> THEN read claims\n(see the JWT skill)" },
        { term: "Audit every mutation", desc: "Append-only log of every grant/revoke/edit, who and when", code: "audit_log.write(actor, action='grant',\n  role='admin', target_user=id, ts=now())" },
        { term: "Metrics", desc: "Track allow/deny rate per endpoint and cache hit rate", code: "Counter('authz_decisions_total',\n  labels=['endpoint','decision'])" },
        { term: "Negative-path testing", desc: "Assert 403 for a user WITHOUT the permission on every protected route", code: "def test_viewer_cannot_approve():\n  assert client.post(url, headers=viewer).status_code == 403" },
        { term: "RBAC vs ABAC vs ReBAC", desc: "Job-function-shaped vs attribute/context-shaped vs relationship-graph-shaped", code: "RBAC  -> coarse, role maps to job function\nABAC  -> 'own resources only', time/context rules\nReBAC -> Zanzibar/OpenFGA/SpiceDB relationship graphs" },
        { term: "When to add ABAC", desc: "The moment access depends on a specific resource instance, not just the role", code: "see ABAC skill — the next step up in flexibility" },
        { term: "AI agents get roles too", desc: "Scope an agent's tool-calling layer to a minimal role, same as a human user", code: "agent_role = Role(permissions={'search:read'})\nnever: agent_role = Role(permissions=ALL)" },
        { term: "Seed via migration", desc: "Roles/permissions are config — versioned, reviewed, never hand-edited in prod", code: "op.bulk_insert(role_table, [{'name': 'viewer'}, ...])" },
      ],
    },
  ],
};

export default rbac;
