import type { CheatSheetData } from "./types";

const terraform: CheatSheetData = {
  title: "The Ultimate Terraform Cheat Sheet",
  subtitle: "Core workflow · HCL syntax · state & graph · modules · production toolbelt",
  sections: [
    {
      title: "Core Workflow & CLI",
      color: "violet",
      rows: [
        { term: "terraform init", desc: "Download providers/modules, configure the backend", code: "terraform init\nterraform init -upgrade   # refresh provider versions" },
        { term: "terraform plan", desc: "Dry run — shows create/update/destroy diff, no real changes", code: "terraform plan\nterraform plan -out=tfplan   # save the exact plan" },
        { term: "terraform apply", desc: "Make real infrastructure match the config", code: "terraform apply\nterraform apply tfplan   # apply a saved, reviewed plan" },
        { term: "terraform destroy", desc: "Tear down everything this config manages, reverse-dependency order", code: "terraform destroy\nterraform destroy -target=aws_instance.web" },
        { term: "terraform fmt / validate", desc: "Canonical formatting and syntax/reference check, no API calls", code: "terraform fmt -recursive\nterraform validate" },
        { term: "terraform console", desc: "Interactive REPL to test expressions against current state", code: "terraform console\n> cidrsubnet(\"10.0.0.0/16\", 8, 3)" },
        { term: "terraform show", desc: "Print current state or a saved plan, human-readable or JSON", code: "terraform show\nterraform show -json tfplan | jq ." },
        { term: "terraform workspace", desc: "Manage multiple isolated state files from one config", code: "terraform workspace new staging\nterraform workspace select staging\nterraform workspace list" },
        { term: "terraform state list/show", desc: "Inspect tracked resource addresses and their attributes", code: "terraform state list\nterraform state show aws_instance.web" },
        { term: "terraform state mv", desc: "Rename/refactor a resource address without destroy+create", code: "terraform state mv aws_instance.old aws_instance.new" },
        { term: "terraform import", desc: "Bring an existing, hand-created resource under management", code: "terraform import aws_s3_bucket.logs my-bucket-name" },
        { term: "terraform force-unlock", desc: "Release a stuck state lock — only after confirming no live run", code: "terraform force-unlock LOCK_ID" },
        { term: "-detailed-exitcode", desc: "Scriptable drift check: 0=no changes, 1=error, 2=changes", code: "terraform plan -detailed-exitcode\necho $?   # 2 means drift detected" },
        { term: "TF_LOG", desc: "Verbose internal + provider RPC logging for debugging", code: "TF_LOG=DEBUG terraform apply 2> debug.log" },
      ],
    },
    {
      title: "HCL Core Blocks",
      color: "blue",
      rows: [
        { term: "terraform block", desc: "Pin required providers and Terraform core version", code: "terraform {\n  required_providers {\n    aws = { source = \"hashicorp/aws\", version = \"~> 5.0\" }\n  }\n  required_version = \">= 1.6\"\n}" },
        { term: "provider block", desc: "Configure a provider plugin (region, credentials, endpoints)", code: "provider \"aws\" {\n  region = \"us-east-1\"\n}" },
        { term: "resource block", desc: "Declare a real object Terraform creates and manages", code: "resource \"aws_instance\" \"web\" {\n  ami           = data.aws_ami.latest.id\n  instance_type = var.instance_type\n}" },
        { term: "data block", desc: "Read-only lookup of something that already exists", code: "data \"aws_vpc\" \"default\" {\n  default = true\n}" },
        { term: "variable block", desc: "A typed, documented input to the configuration", code: "variable \"instance_type\" {\n  type        = string\n  default     = \"t3.micro\"\n  description = \"EC2 size\"\n}" },
        { term: "output block", desc: "Surface a value after apply; other configs can consume it", code: "output \"public_ip\" {\n  value     = aws_instance.web.public_ip\n  sensitive = false\n}" },
        { term: "locals block", desc: "Named expressions scoped to the module, avoid repetition", code: "locals {\n  common_tags = { ManagedBy = \"terraform\", Env = var.env }\n}" },
        { term: "module block", desc: "Call a reusable directory of config like a function", code: "module \"network\" {\n  source      = \"../../modules/network\"\n  environment = \"staging\"\n}" },
        { term: "backend block", desc: "Where state is stored — always remote for team use", code: "terraform {\n  backend \"s3\" {\n    bucket = \"my-tfstate\"\n    key    = \"prod/network.tfstate\"\n    region = \"us-east-1\"\n  }\n}" },
      ],
    },
    {
      title: "Everyday Idioms",
      color: "emerald",
      rows: [
        { term: "Attribute reference", desc: "Reference another resource's computed attribute (HCL2, no interpolation braces needed)", code: "vpc_id = aws_vpc.main.id\nsubnet_id = aws_subnet.app.id" },
        { term: "for_each (map/set)", desc: "One resource per key — stable identity, safe add/remove", code: "resource \"aws_s3_bucket\" \"data\" {\n  for_each = toset([\"logs\", \"backups\"])\n  bucket   = \"myapp-\" + each.value\n}" },
        { term: "count", desc: "N copies addressed by numeric index — fragile on reorder", code: "resource \"aws_instance\" \"w\" {\n  count = 3\n  tags  = { Name = \"worker-\" + count.index }\n}" },
        { term: "Conditional expression", desc: "Ternary-style value selection", code: "instance_type = var.env == \"prod\" ? \"m5.large\" : \"t3.micro\"" },
        { term: "merge()", desc: "Combine maps — common for tag sets", code: "tags = merge(local.common_tags, { Name = \"web\" })" },
        { term: "cidrsubnet()", desc: "Derive a subnet CIDR from a parent VPC CIDR", code: "cidrsubnet(var.vpc_cidr, 8, 1)   # 10.0.1.0/24 from 10.0.0.0/16" },
        { term: "toset() / tolist()", desc: "Type conversions for for_each and iteration", code: "for_each = toset(var.bucket_names)" },
        { term: "terraform_remote_state", desc: "Consume another config's outputs across state boundaries", code: "data \"terraform_remote_state\" \"net\" {\n  backend = \"s3\"\n  config  = { bucket = \"tfstate\", key = \"net.tfstate\" }\n}\n# use: data.terraform_remote_state.net.outputs.vpc_id" },
        { term: ".tfvars files", desc: "Supply variable values without editing resource blocks", code: "terraform apply -var-file=\"prod.tfvars\"" },
        { term: "moved block", desc: "Record a resource rename/refactor declaratively", code: "moved {\n  from = aws_instance.old_name\n  to   = aws_instance.new_name\n}" },
      ],
    },
    {
      title: "Power Features",
      color: "amber",
      rows: [
        { term: "lifecycle.prevent_destroy", desc: "Refuse to destroy a specific irreplaceable resource", code: "lifecycle {\n  prevent_destroy = true\n}" },
        { term: "lifecycle.create_before_destroy", desc: "Zero-downtime replace — new resource up before old one dies", code: "lifecycle {\n  create_before_destroy = true\n}" },
        { term: "lifecycle.ignore_changes", desc: "Ignore drift on a specific attribute during plan", code: "lifecycle {\n  ignore_changes = [tags[\"LastPatched\"]]\n}" },
        { term: "depends_on", desc: "Force an explicit ordering with no data dependency — last resort", code: "resource \"aws_instance\" \"web\" {\n  depends_on = [aws_iam_role_policy.attach]\n}" },
        { term: "Dependency graph", desc: "Built from attribute references; independent nodes run in parallel", code: "# vpc -> subnet -> instance is a strict chain\n# unrelated resources apply concurrently (default: 10)" },
        { term: "State locking", desc: "DynamoDB (or backend-native) prevents concurrent-apply corruption", code: "dynamodb_table = \"terraform-locks\"   # in the s3 backend block" },
        { term: "native tests", desc: "Plan- or apply-based assertions in .tftest.hcl files", code: "run \"check_cidr\" {\n  command = plan\n  assert {\n    condition = aws_subnet.app.cidr_block == \"10.0.1.0/24\"\n    error_message = \"CIDR mismatch\"\n  }\n}" },
        { term: "Sensitive variables", desc: "Redact a value from CLI output (not encryption)", code: "variable \"db_password\" {\n  type      = string\n  sensitive = true\n}" },
        { term: "Provider aliasing", desc: "Manage resources across multiple regions/accounts in one config", code: "provider \"aws\" {\n  alias  = \"west\"\n  region = \"us-west-2\"\n}\nresource \"aws_instance\" \"w\" { provider = aws.west }" },
      ],
    },
    {
      title: "Pitfalls & Gotchas",
      color: "rose",
      rows: [
        { term: "auto-approve in shared envs", desc: "Skips the human review gate — reserve for reviewed plan files only", code: "# risky: terraform apply -auto-approve  (staging/prod)\n# safe: terraform apply tfplan  (already reviewed)" },
        { term: "count reorder bug", desc: "Removing a middle list item renumbers and replaces later resources", code: "# use for_each with a set/map instead of count for growable lists" },
        { term: "Hand-editing state", desc: "Desyncs Terraform's records from what its own commands expect", code: "# never: vim terraform.tfstate\n# instead: terraform state mv / import / moved block" },
        { term: "Local state on a team project", desc: "No locking, no sharing — one crash desyncs state from reality", code: "# always configure a remote backend for any multi-person project" },
        { term: "Provisioners as config management", desc: "No drift detection, imperative, HashiCorp calls it last resort", code: "# prefer user_data/cloud-init or a pre-baked image (Packer)" },
        { term: "Monolithic state file", desc: "Slow plans, high lock contention, account-wide blast radius", code: "# split state by environment/team ownership instead" },
        { term: "Unpinned provider versions", desc: "A silent major upgrade can change resource schema mid-project", code: "version = \"~> 5.0\"   # constrain, and commit .terraform.lock.hcl" },
        { term: "Ignoring \"-/+\" in plan", desc: "Marks destroy-then-recreate — a data-loss risk on stateful resources", code: "# read every plan; treat replace on a database as a stop sign" },
        { term: "Secrets in .tfvars/state", desc: "State stores plaintext resource attributes, including secrets", code: "# source secrets from a vault; never commit *.tfvars with real values" },
      ],
    },
    {
      title: "Production Toolbelt",
      color: "cyan",
      rows: [
        { term: "Remote backend (S3+lock)", desc: "Team-safe state storage with encryption and locking", code: "backend \"s3\" {\n  bucket = \"tfstate\"\n  key    = \"prod/app.tfstate\"\n  dynamodb_table = \"terraform-locks\"\n  encrypt = true\n}" },
        { term: "CI plan-then-apply", desc: "plan on every PR (reviewed), apply only after merge + approval", code: "# GitHub Actions: plan job on pull_request\n# apply job on push to main, environment: production gate" },
        { term: "tfsec / Checkov", desc: "Static security scanning of HCL — no provider API calls needed", code: "tfsec .\ncheckov -d ." },
        { term: "Infracost", desc: "Estimate the dollar cost delta of a plan before merge", code: "infracost breakdown --path .\ninfracost diff --path ." },
        { term: "OPA / Conftest", desc: "Policy-as-code checks against the plan's JSON output", code: "terraform show -json tfplan > plan.json\nconftest test plan.json" },
        { term: "Drift detection job", desc: "Scheduled plan with no apply; alert on detected changes", code: "terraform plan -detailed-exitcode || [ $? -eq 2 ] && alert" },
        { term: ".terraform.lock.hcl", desc: "Provider version lockfile — commit for reproducible installs", code: "# generated by init; always commit alongside .tf files" },
        { term: "Module versioning", desc: "Pin module sources to a tag, not a floating branch", code: "module \"network\" {\n  source  = \"git::https://example.com/modules.git//network?ref=v1.2.0\"\n}" },
        { term: "Terratest", desc: "Go library for real apply-and-verify integration tests of modules", code: "// Go: terraform.InitAndApply(t, opts); assert on live resources" },
        { term: "Secrets Management link", desc: "Keep generated secrets (DB passwords) out of plaintext state", code: "# store the generated value in a vault immediately after creation" },
      ],
    },
  ],
};

export default terraform;
